In [ ]:
# Updating Rows and columns and Modifying Data within the DataFrames

In [1]:
import pandas as pd

In [2]:
people = { "first_name" : ["Smith","Rowan","Alfie"],
           "last_name" : ["Will","John","Haze"],
           "age" : ["34", "45","23"],
           "email" : ["smithwill@gmail.com", "rowanjohn@gmail.com", "alfiehaze@gmail.com"]}

In [3]:
people_df = pd.DataFrame(people)
people_df

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan      John  45  rowanjohn@gmail.com
2      Alfie      Haze  23  alfiehaze@gmail.com

In [4]:

# Updating columns

people_df.columns = [x.upper() for x in people_df.columns]

In [5]:
people_df

  FIRST_NAME LAST_NAME AGE                EMAIL
0      Smith      Will  34  smithwill@gmail.com
1      Rowan      John  45  rowanjohn@gmail.com
2      Alfie      Haze  23  alfiehaze@gmail.com

In [6]:
people_df.columns = people_df.columns.str.replace('_',' ')

In [7]:
people_df

  FIRST NAME LAST NAME AGE                EMAIL
0      Smith      Will  34  smithwill@gmail.com
1      Rowan      John  45  rowanjohn@gmail.com
2      Alfie      Haze  23  alfiehaze@gmail.com

In [8]:
people_df.columns = people_df.columns.str.replace(' ', '_')

In [9]:
people_df

  FIRST_NAME LAST_NAME AGE                EMAIL
0      Smith      Will  34  smithwill@gmail.com
1      Rowan      John  45  rowanjohn@gmail.com
2      Alfie      Haze  23  alfiehaze@gmail.com

In [10]:
people_df.columns = [x.lower() for x in people_df.columns]

In [11]:
people_df

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan      John  45  rowanjohn@gmail.com
2      Alfie      Haze  23  alfiehaze@gmail.com

In [13]:

# rename a particular column name

people_df.rename(columns = {"first_name" : "first", "last_name" : "last"}, inplace=True)

In [14]:
people_df

   first  last age                email
0  Smith  Will  34  smithwill@gmail.com
1  Rowan  John  45  rowanjohn@gmail.com
2  Alfie  Haze  23  alfiehaze@gmail.com

In [21]:

# updating a single row of data

people_df.loc[2] = ['Alfie', 'William', '23', 'alfiewilliam@gamil.com']

In [22]:
people_df

  first_name last_name age                   email
0      Smith      Will  34     smithwill@gmail.com
1      Rowan      John  45     rowanjohn@gmail.com
2      Alfie   William  23  alfiewilliam@gamil.com

In [23]:
people_df.loc[2,['last_name', 'email']] = ['John', 'alfiejohn@gmail.com']

In [24]:
people_df

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan      John  45  rowanjohn@gmail.com
2      Alfie      John  23  alfiejohn@gmail.com

In [25]:
people_df.at[2,'last_name'] = 'Smith'

In [26]:
people_df

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan      John  45  rowanjohn@gmail.com
2      Alfie     Smith  23  alfiejohn@gmail.com

In [27]:
people_df.at[2, 'last_name'] = 'John'

In [28]:
people_df

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan      John  45  rowanjohn@gmail.com
2      Alfie      John  23  alfiejohn@gmail.com

In [29]:
filt = people_df['email'] == 'alfiejohn@gmail.com'

In [30]:
people_df[filt]

  first_name last_name age                email
2      Alfie      John  23  alfiejohn@gmail.com

In [32]:
people_df.loc[filt,'last_name']

2    John
Name: last_name, dtype: object

In [33]:
people_df.loc[filt,'last_name'] = 'Smith'

In [34]:
people_df

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan      John  45  rowanjohn@gmail.com
2      Alfie     Smith  23  alfiejohn@gmail.com

In [35]:
people_df.loc[filt,'last_name'] = 'John'

In [36]:
people_df

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan      John  45  rowanjohn@gmail.com
2      Alfie      John  23  alfiejohn@gmail.com

In [37]:

# updating multiple rows

people_df['email'].str.upper()

0    SMITHWILL@GMAIL.COM
1    ROWANJOHN@GMAIL.COM
2    ALFIEJOHN@GMAIL.COM
Name: email, dtype: object

In [38]:
people_df['email'] = people_df['email'].str.upper()

In [39]:
people_df

  first_name last_name age                email
0      Smith      Will  34  SMITHWILL@GMAIL.COM
1      Rowan      John  45  ROWANJOHN@GMAIL.COM
2      Alfie      John  23  ALFIEJOHN@GMAIL.COM

In [40]:
people_df['email'] = people_df['email'].str.lower()

In [41]:
people_df

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan      John  45  rowanjohn@gmail.com
2      Alfie      John  23  alfiejohn@gmail.com

In [44]:

# there are 4 methods to upadate multiple rows

# 1. apply

people_df['email'].apply(len)

0    19
1    19
2    19
Name: email, dtype: int64

In [65]:
def update_email(email):
    return email.upper()

In [ ]:
people_df['email'].apply(update_email)

In [49]:
people_df

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan      John  45  rowanjohn@gmail.com
2      Alfie      John  23  alfiejohn@gmail.com

In [50]:
people_df['email'] = people_df['email'].apply(update_email)

In [51]:
people_df

  first_name last_name age                email
0      Smith      Will  34  SMITHWILL@GMAIL.COM
1      Rowan      John  45  ROWANJOHN@GMAIL.COM
2      Alfie      John  23  ALFIEJOHN@GMAIL.COM

In [60]:
type(people_df.loc[0, 'email'])

builtin_function_or_method

In [69]:
# people_df['email'] = people_df['email'].str.lower()

In [71]:
# people_df['email'].apply(type).value_counts()

email
<class 'float'>    3
Name: count, dtype: int64

In [ ]:
# applying apply() on dataframe

In [5]:
people_df

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan      John  45  rowanjohn@gmail.com
2      Alfie      Haze  23  alfiehaze@gmail.com

In [4]:
people_df.apply(len)

first_name    3
last_name     3
age           3
email         3
dtype: int64

In [6]:
people_df.apply(pd.Series.min)

first_name                  Alfie
last_name                    Haze
age                            23
email         alfiehaze@gmail.com
dtype: object

In [7]:
people_df.apply(min)

first_name                  Alfie
last_name                    Haze
age                            23
email         alfiehaze@gmail.com
dtype: object

In [8]:

# applymap() method

people_df.applymap(len)

/var/folders/55/d6806_zn1l39xvg_qlwf_tn00000gn/T/ipykernel_1373/123506584.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  people_df.applymap(len)

   first_name  last_name  age  email
0           5          4    2     19
1           5          4    2     19
2           5          4    2     19

In [10]:
people_df['first_name'].map({"Smith":"Liam","Rowan":"Mike"})

0    Liam
1    Mike
2     NaN
Name: first_name, dtype: object

In [11]:
people_df["first_name"].replace({"Smith":"Liam","Rowan":"Mike"})

0     Liam
1     Mike
2    Alfie
Name: first_name, dtype: object