In [1]:
import pandas as pd
import numpy as np

In [2]:
people = {
    'first_name': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'], 
    'last_name': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

In [3]:
df = pd.DataFrame(people)

In [4]:
df

  first_name last_name                    email      age
0      Corey   Schafer  CoreyMSchafer@gmail.com       33
1       Jane       Doe        JaneDoe@email.com       55
2       John       Doe        JohnDoe@email.com       63
3      Chris   Schafer                     None       36
4        NaN       NaN                      NaN     None
5       None       NaN      Anonymous@email.com     None
6         NA   Missing                       NA  Missing

In [5]:
df.dropna()

  first_name last_name                    email      age
0      Corey   Schafer  CoreyMSchafer@gmail.com       33
1       Jane       Doe        JaneDoe@email.com       55
2       John       Doe        JohnDoe@email.com       63
6         NA   Missing                       NA  Missing

In [6]:
df.dropna(axis='index', how='any')

  first_name last_name                    email      age
0      Corey   Schafer  CoreyMSchafer@gmail.com       33
1       Jane       Doe        JaneDoe@email.com       55
2       John       Doe        JohnDoe@email.com       63
6         NA   Missing                       NA  Missing

In [7]:
df.dropna(axis='index', how='all')

  first_name last_name                    email      age
0      Corey   Schafer  CoreyMSchafer@gmail.com       33
1       Jane       Doe        JaneDoe@email.com       55
2       John       Doe        JohnDoe@email.com       63
3      Chris   Schafer                     None       36
5       None       NaN      Anonymous@email.com     None
6         NA   Missing                       NA  Missing

In [8]:
df.dropna(axis='columns', how='all')

  first_name last_name                    email      age
0      Corey   Schafer  CoreyMSchafer@gmail.com       33
1       Jane       Doe        JaneDoe@email.com       55
2       John       Doe        JohnDoe@email.com       63
3      Chris   Schafer                     None       36
4        NaN       NaN                      NaN     None
5       None       NaN      Anonymous@email.com     None
6         NA   Missing                       NA  Missing

In [9]:
df.dropna(axis='columns', how='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [10]:
df.dropna(axis='index', how='any', subset=['last_name'])

  first_name last_name                    email      age
0      Corey   Schafer  CoreyMSchafer@gmail.com       33
1       Jane       Doe        JaneDoe@email.com       55
2       John       Doe        JohnDoe@email.com       63
3      Chris   Schafer                     None       36
6         NA   Missing                       NA  Missing

In [11]:

df.dropna(axis='index', how='any', subset=['last_name','email'])

  first_name last_name                    email      age
0      Corey   Schafer  CoreyMSchafer@gmail.com       33
1       Jane       Doe        JaneDoe@email.com       55
2       John       Doe        JohnDoe@email.com       63
6         NA   Missing                       NA  Missing

In [12]:
df.dropna(axis='index', how='all', subset=['last_name','email'])

  first_name last_name                    email      age
0      Corey   Schafer  CoreyMSchafer@gmail.com       33
1       Jane       Doe        JaneDoe@email.com       55
2       John       Doe        JohnDoe@email.com       63
3      Chris   Schafer                     None       36
5       None       NaN      Anonymous@email.com     None
6         NA   Missing                       NA  Missing

In [13]:
df.isna()

   first_name  last_name  email    age
0       False      False  False  False
1       False      False  False  False
2       False      False  False  False
3       False      False   True  False
4        True       True   True   True
5        True       True  False   True
6       False      False  False  False

In [14]:
df.fillna(0)

  first_name last_name                    email      age
0      Corey   Schafer  CoreyMSchafer@gmail.com       33
1       Jane       Doe        JaneDoe@email.com       55
2       John       Doe        JohnDoe@email.com       63
3      Chris   Schafer                        0       36
4          0         0                        0        0
5          0         0      Anonymous@email.com        0
6         NA   Missing                       NA  Missing

In [15]:
df.dropna(axis='index', how='any')

  first_name last_name                    email      age
0      Corey   Schafer  CoreyMSchafer@gmail.com       33
1       Jane       Doe        JaneDoe@email.com       55
2       John       Doe        JohnDoe@email.com       63
6         NA   Missing                       NA  Missing

In [20]:
df

  first_name last_name                    email      age
0      Corey   Schafer  CoreyMSchafer@gmail.com       33
1       Jane       Doe        JaneDoe@email.com       55
2       John       Doe        JohnDoe@email.com       63
3      Chris   Schafer                     None       36
4        NaN       NaN                      NaN     None
5       None       NaN      Anonymous@email.com     None
6         NA   Missing                       NA  Missing

In [ ]:
ff.fillna(0)

In [16]:
df.dtypes

first_name    object
last_name     object
email         object
age           object
dtype: object

In [17]:
df['age'].mean()

TypeError: can only concatenate str (not "int") to str

In [27]:
df['age'] = df['age'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [26]:
type(np.nan)

float

In [21]:
# Replace 'Missing' with NaN
df['age'] = df['age'].replace('Missing', np.nan)

In [22]:
df['age'] = df['age'].astype(float)

In [23]:
df.dtypes

first_name     object
last_name      object
email          object
age           float64
dtype: object

In [24]:
df['age'].mean()

np.float64(46.75)