In [1]:
import pandas as pd

In [3]:
people = { "first_name" : ["Smith","Rowan","Alfie","John"],
           "last_name" : ["Will","Doe","Doe","Doe"],
           "age" : ["34", "45","23","45"],
           "email" : ["smithwill@gmail.com", "rowanjohn@gmail.com", "alfiehaze@gmail.com", "johndoe@gmail.com"]}

In [4]:
people_df = pd.DataFrame(people)

In [5]:
people_df

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan       Doe  45  rowanjohn@gmail.com
2      Alfie       Doe  23  alfiehaze@gmail.com
3       John       Doe  45    johndoe@gmail.com

In [6]:
people_df.sort_values(by = 'last_name')

  first_name last_name age                email
1      Rowan       Doe  45  rowanjohn@gmail.com
2      Alfie       Doe  23  alfiehaze@gmail.com
3       John       Doe  45    johndoe@gmail.com
0      Smith      Will  34  smithwill@gmail.com

In [8]:
people_df.sort_values(by = 'last_name', ascending = False)

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan       Doe  45  rowanjohn@gmail.com
2      Alfie       Doe  23  alfiehaze@gmail.com
3       John       Doe  45    johndoe@gmail.com

In [10]:
people_df.sort_values(by = ['last_name', 'first_name'])

  first_name last_name age                email
2      Alfie       Doe  23  alfiehaze@gmail.com
3       John       Doe  45    johndoe@gmail.com
1      Rowan       Doe  45  rowanjohn@gmail.com
0      Smith      Will  34  smithwill@gmail.com

In [13]:
people_df.sort_values(by = ['last_name', 'first_name'], ascending =[False, True])

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
2      Alfie       Doe  23  alfiehaze@gmail.com
3       John       Doe  45    johndoe@gmail.com
1      Rowan       Doe  45  rowanjohn@gmail.com

In [14]:
people_df

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan       Doe  45  rowanjohn@gmail.com
2      Alfie       Doe  23  alfiehaze@gmail.com
3       John       Doe  45    johndoe@gmail.com

In [15]:
people_df.sort_values(by = ['last_name', 'first_name'], ascending =[False, True], inplace =True)

In [16]:
people_df

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
2      Alfie       Doe  23  alfiehaze@gmail.com
3       John       Doe  45    johndoe@gmail.com
1      Rowan       Doe  45  rowanjohn@gmail.com

In [21]:
people_df.sort_index()

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan       Doe  45  rowanjohn@gmail.com
2      Alfie       Doe  23  alfiehaze@gmail.com
3       John       Doe  45    johndoe@gmail.com

In [17]:
df = pd.read_csv('survey_results_public.csv', low_memory=False)

In [18]:
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [19]:
schema_df = pd.read_csv('survey_results_schema.csv')

In [20]:
schema_df

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...,...
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

df.sort_values(by = 'Country')

In [22]:
df.sort_values(by = 'Country')

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
6835,6836,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Technical documentation...,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I’m stuck and can’t explain the problem,AI,NaN,10.0
6009,6010,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",5.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,Llama Index;Ollama;OpenRouter,NaN,Sentry;Grafana + Prometheus,NaN,ChatGPT;GitHub Copilot;Tabnine;Lovable.dev,NaN,I don’t think I’ll need help from people anymore,Problem-Solving and Critical Thinking,986.0,8.0
15707,15708,I am a developer by profession,Prefer not to say,NaN,"Independent contractor, freelancer, or self-em...",Transitioning to retirement (gradually reducin...,NaN,"Yes, I am new to coding or currently a student",Games or coding challenges,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7076,7077,"I am not primarily a developer, but I write co...",25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (less than 10 hours per w...,7.0,"Yes, I am new to coding or currently a student",AI CodeGen tools or AI-enabled apps,"Yes, I learned how to use AI-enabled tools req...",...,Ollama,NaN,Metero,NaN,ChatGPT;Google Gemini;AgentGPT;Perplexity,NaN,When I’m stuck and can’t explain the problem,yes,8450.0,NaN
19815,19816,I am learning to code,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,None of the above;Attending school (part-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49185,49186,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df['Country']

0            Ukraine
1        Netherlands
2            Ukraine
3            Ukraine
4            Ukraine
            ...
49186            NaN
49187            NaN
49188          Italy
49189            NaN
49190            NaN
Name: Country, Length: 49191, dtype: object

In [25]:
df.sort_values(by = 'Country', inplace = True)

In [26]:
df.head(10)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
6835,6836,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Technical documentation...,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I’m stuck and can’t explain the problem,AI,NaN,10.0
6009,6010,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",5.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,Llama Index;Ollama;OpenRouter,NaN,Sentry;Grafana + Prometheus,NaN,ChatGPT;GitHub Copilot;Tabnine;Lovable.dev,NaN,I don’t think I’ll need help from people anymore,Problem-Solving and Critical Thinking,986.0,8.0
15707,15708,I am a developer by profession,Prefer not to say,NaN,"Independent contractor, freelancer, or self-em...",Transitioning to retirement (gradually reducin...,NaN,"Yes, I am new to coding or currently a student",Games or coding challenges,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7076,7077,"I am not primarily a developer, but I write co...",25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (less than 10 hours per w...,7.0,"Yes, I am new to coding or currently a student",AI CodeGen tools or AI-enabled apps,"Yes, I learned how to use AI-enabled tools req...",...,Ollama,NaN,Metero,NaN,ChatGPT;Google Gemini;AgentGPT;Perplexity,NaN,When I’m stuck and can’t explain the problem,yes,8450.0,NaN
19815,19816,I am learning to code,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,None of the above;Attending school (part-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44796,44797,"I am not primarily a developer, but I write co...",Prefer not to say,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",Volunteering (regularly);Engaged in paid work ...,30.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to compare different solutions;Whe...,Being able to perform real coding. Not the aut...,NaN,NaN
45924,45925,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Volunteering (regularly),9.0,"Yes, I am not new to coding but am learning ne...",AI CodeGen tools or AI-enabled apps;Blogs or p...,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7042.0,NaN
27098,27099,I am a developer by profession,18-24 years old,Some college/university study without earning ...,Student,None of the above,NaN,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I have et...,NaN,NaN,8.0
40306,40307,I am a developer by profession,25-34 years old,Primary/elementary school,Employed,Engaged in paid work (20-29 hours per week),8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,ChatGPT;GitHub Copilot;Microsoft Copilot,NaN,When I don’t trust AI’s answers;When I want to...,I think the soft skills will be very useful,9858.0,5.0
40966,40967,I am a developer by profession,18-24 years old,"Secondary school (e.g. American high school, G...",Employed,Volunteering (regularly);Engaged in paid work ...,8.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,65000.0,10.0

In [27]:
df['Country'].head(50)

6835     Afghanistan
6009     Afghanistan
15707    Afghanistan
7076     Afghanistan
19815    Afghanistan
44796    Afghanistan
45924    Afghanistan
27098    Afghanistan
40306    Afghanistan
40966    Afghanistan
38608    Afghanistan
7924     Afghanistan
7166     Afghanistan
37730        Albania
14757        Albania
36996        Albania
48949        Albania
28587        Albania
2022         Albania
35183        Albania
16238        Albania
33939        Albania
45420        Albania
3887         Albania
44878        Albania
44945        Albania
35933        Albania
22399        Albania
8775         Albania
11873        Albania
41906        Albania
27801        Albania
16849        Albania
25303        Albania
3184         Albania
44462        Algeria
35358        Algeria
33029        Algeria
1840         Algeria
47922        Algeria
14679        Algeria
7105         Algeria
41295        Algeria
46635        Algeria
25844        Algeria
28487        Algeria
34028        Algeria
2540         Algeria
41257        Algeria
14529        Algeria
Name: Country, dtype: object

In [31]:
df[['Country','ConvertedCompYearly']].head(50)

           Country  ConvertedCompYearly
6835   Afghanistan                  NaN
6009   Afghanistan                986.0
15707  Afghanistan                  NaN
7076   Afghanistan               8450.0
19815  Afghanistan                  NaN
44796  Afghanistan                  NaN
45924  Afghanistan               7042.0
27098  Afghanistan                  NaN
40306  Afghanistan               9858.0
40966  Afghanistan              65000.0
38608  Afghanistan               1000.0
7924   Afghanistan                282.0
7166   Afghanistan               5200.0
37730      Albania              67779.0
14757      Albania              34804.0
36996      Albania                  NaN
48949      Albania              17402.0
28587      Albania             118286.0
2022       Albania             139218.0
35183      Albania                  NaN
16238      Albania                  NaN
33939      Albania              17734.0
45420      Albania                  NaN
3887       Albania              14187.0
44878      Albania                  NaN
44945      Albania                  NaN
35933      Albania              50000.0
22399      Albania                 15.0
8775       Albania                  NaN
11873      Albania                  NaN
41906      Albania                  NaN
27801      Albania                  8.0
16849      Albania                236.0
25303      Albania                  NaN
3184       Albania             116014.0
44462      Algeria                  NaN
35358      Algeria                  NaN
33029      Algeria                  NaN
1840       Algeria               4438.0
47922      Algeria                  NaN
14679      Algeria                  NaN
7105       Algeria                  NaN
41295      Algeria              98612.0
46635      Algeria               2400.0
25844      Algeria                185.0
28487      Algeria                  NaN
34028      Algeria               1109.0
2540       Algeria                  NaN
41257      Algeria                  NaN
14529      Algeria                  NaN

In [35]:
df.sort_values(by =['Country','ConvertedCompYearly'], ascending =[True, False], inplace= True)

In [36]:
df[['Country','ConvertedCompYearly']].head(50)

           Country  ConvertedCompYearly
40966  Afghanistan              65000.0
40306  Afghanistan               9858.0
7076   Afghanistan               8450.0
45924  Afghanistan               7042.0
7166   Afghanistan               5200.0
38608  Afghanistan               1000.0
6009   Afghanistan                986.0
7924   Afghanistan                282.0
6835   Afghanistan                  NaN
15707  Afghanistan                  NaN
19815  Afghanistan                  NaN
44796  Afghanistan                  NaN
27098  Afghanistan                  NaN
2022       Albania             139218.0
28587      Albania             118286.0
3184       Albania             116014.0
37730      Albania              67779.0
35933      Albania              50000.0
14757      Albania              34804.0
33939      Albania              17734.0
48949      Albania              17402.0
3887       Albania              14187.0
16849      Albania                236.0
22399      Albania                 15.0
27801      Albania                  8.0
36996      Albania                  NaN
35183      Albania                  NaN
16238      Albania                  NaN
45420      Albania                  NaN
44878      Albania                  NaN
44945      Albania                  NaN
8775       Albania                  NaN
11873      Albania                  NaN
41906      Albania                  NaN
25303      Albania                  NaN
41295      Algeria              98612.0
37618      Algeria              50000.0
26445      Algeria              23114.0
1540       Algeria              20883.0
23090      Algeria              12000.0
29464      Algeria               7705.0
16685      Algeria               7088.0
30106      Algeria               6472.0
1840       Algeria               4438.0
31351      Algeria               3852.0
46635      Algeria               2400.0
14547      Algeria               1156.0
34028      Algeria               1109.0
25844      Algeria                185.0
11321      Algeria                 17.0

In [37]:
df['ConvertedCompYearly'].nlargest(50)

34267    50000000.0
28700    33552715.0
43143    18387548.0
35353    15430267.0
45971    13921760.0
48428    10000000.0
24900     9531653.0
10025     9000000.0
37352     6890299.0
30728     6371285.0
40418     6000000.0
19536     5810837.0
28055     5000000.0
14873     4706124.0
48023     3900562.0
28058     3900000.0
39349     3821169.0
25268     2500000.0
5410      2346000.0
34975     2000000.0
5327      1950000.0
40518     1820367.0
38007     1740220.0
15411     1700000.0
31876     1555205.0
9310      1500000.0
3265      1500000.0
11938     1497556.0
42326     1361415.0
2668      1300000.0
12055     1300000.0
22510     1279775.0
2725      1250000.0
38750     1239929.0
48839     1225273.0
27935     1200000.0
2812      1200000.0
19059     1160147.0
4583      1160147.0
32037     1160147.0
4842      1100000.0
31678     1100000.0
2087      1044132.0
14357     1036327.0
45555     1021061.0
2009      1006403.0
13860     1000000.0
42481     1000000.0
28794     1000000.0
48177     1000000.0
Name: ConvertedCompYearly, dtype: float64

In [38]:
df.nlargest(10,'ConvertedCompYearly')

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
34267,34268,I code primarily as a hobby,55-64 years old,"Associate degree (A.A., A.S., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000000.0,NaN
28700,28701,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),20.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,ChatGPT;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I have et...,NaN,33552715.0,7.0
43143,43144,I code primarily as a hobby,18-24 years old,"Associate degree (A.A., A.S., etc.)",Employed,Engaged in paid work (20-29 hours per week);En...,10.0,"Yes, I am not new to coding but am learning ne...",Other (please specify):,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,being laid off,18387548.0,NaN
35353,35354,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),15.0,"No, I am not new to coding and did not learn n...",NaN,NaN,...,NaN,NaN,NaN,NaN,ChatGPT;Google Gemini,NaN,When I’m stuck and can’t explain the problem,NaN,15430267.0,8.0
45971,45972,I work with developers or my work supports dev...,55-64 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),30.0,"Yes, I am not new to coding but am learning ne...",Colleague or on-the-job training,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13921760.0,NaN
48428,48429,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (10-19 hours per week);En...,NaN,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10000000.0,NaN
24900,24901,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something;When...,NaN,9531653.0,4.0
10025,10026,I am a developer by profession,25-34 years old,Primary/elementary school,Employed,Attending school (full-time),2.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Everything,9000000.0,9.0
37352,37353,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",Volunteering (regularly),15.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something;When...,"All the same: right tools for proper tasks, co...",6890299.0,7.0
30728,30729,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Attending school (part-time);Engaged in paid w...,17.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,"problem synthesis, communication, panoramic vi...",6371285.0,8.0

In [39]:
df.nsmallest(10,'ConvertedCompYearly')

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
34865,34866,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (less than 10 hours per w...,16.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,Ollama,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemi...,NaN,When I don’t trust AI’s answers;When I want to...,all of them,1.0,8.0
41682,41683,"I am not primarily a developer, but I write co...",45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",None of the above,13.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something,AI provides the code but if it is not somethin...,1.0,NaN
34567,34568,I am a developer by profession,25-34 years old,Primary/elementary school,Employed,Volunteering (regularly),8.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0
27892,27893,I am learning to code,35-44 years old,Some college/university study without earning ...,Not employed,None of the above,12.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
28177,28178,I am a developer by profession,18-24 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",Volunteering (regularly);Engaged in paid work ...,1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Solve any problem with logic,1.0,8.0
42078,42079,I work with developers or my work supports dev...,25-34 years old,Some college/university study without earning ...,Student,Attending school (full-time),12.0,"Yes, I am new to coding or currently a student","School (i.e., University, College, etc)","Yes, I learned how to use AI-enabled tools req...",...,Amazon Bedrock Agents,NaN,Adversarial Robustness Toolbox (ART),NaN,OpenHands (formerly OpenDevin),NaN,When I want to fully understand something,Mentioned,1.0,NaN
16489,16490,I am learning to code,18-24 years old,Primary/elementary school,"Independent contractor, freelancer, or self-em...",Volunteering (regularly),1.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
4580,4581,I am a developer by profession,18-24 years old,"Associate degree (A.A., A.S., etc.)",Student,Attending school (full-time);Engaged in paid w...,6.0,"Yes, I am new to coding or currently a student","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I’m stuck and can’t explain the problem,NaN,1.0,8.0
21034,21035,I am a developer by profession,18-24 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Not employed,"Caring for dependents (children, elderly, etc.)",1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,Zapier,NaN,Langfuse,NaN,ChatGPT;Bolt.new,NaN,When I need quick help troubleshooting,Well it will gradually take to a killing path,1.0,6.0
26961,26962,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),11.0,"Yes, I am not new to coding but am learning ne...",AI CodeGen tools or AI-enabled apps,"Yes, I learned how to use AI-enabled tools for...",...,CrewAI;LangChain;LangGraph,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0