In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('survey_results_public.csv', low_memory=False)
schema_df = pd.read_csv('survey_results_schema.csv')

In [3]:

# to display the dataframe completly

pd.set_option('display.max_columns',172)
pd.set_option('display.max_rows',139)

In [4]:

# analyzing the data in the dataframe

df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=172)

In [16]:
df.head(15)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
5,6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,20.0,"Developer, back-end",NaN,NaN,NaN,"Yes, I influenced the purchase of a substantia...",Work,12.0,5.0,4.0,6.0,2.0,10.0,3.0,7.0,8.0,14.0,NaN,12.0,5.0,13.0,10.0,9.0,1.0,4.0,6.0,2.0,15.0,NaN,Fintech,4.0,3.0,5.0,8.0,9.0,2.0,1.0,10.0,11.0,12.0,6.0,13.0,14.0,15.0,7.0,NaN,I'm not sure,I have somewhat considered changing my career ...,5.0,5.0,Ukraine,USD United States dollar,120000.0,Yes,Java;Scala,Java;Kotlin;Scala,Java;Scala,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud;Microso...,Amazon Web Services (AWS),Amazon Web Services (AWS),NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,akka,akka,Yes,IntelliJ IDEA;Visual Studio Code,IntelliJ IDEA;Visual Studio Code,IntelliJ IDEA;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MacOS,MacOS,Azure Devops;GitHub;GitLab;Jira,GitHub;Jira,GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;X;YouTube;Linked...,Stack Overflow;Stack Exchange;X;YouTube;Linked...,Stack Overflow;Stack Exchange;X;YouTube;Linked...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year","Lists of recommendations (tools, frameworks, t...",6.0,NaN,9.0,3.0,4.0,5.0,10.0,1.0,11.0,15.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools daily",Indifferent,Somewhat distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Predictive analytics,Deployment and monitoring,Project planning;Debugging or fixing code;Comm...,Testing code;Learning new concepts or technolo...,"AI solutions that are almost right, but not quite",No it isnt,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,NaN,AI agents have improved the quality of my code...,AI agents have helped me automate repetitive t...,NaN,The cost of using certain AI agent platforms i...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,GitHub Copilot,NaN,When I have ethical or security concerns about...,designing the architecture in the new domain,120000.0,7.0

In [6]:
df['ConvertedCompYearly']

0         61256.0
1        104413.0
2         53061.0
3         36197.0
4         60000.0
           ...
49186         NaN
49187         NaN
49188         NaN
49189         NaN
49190         NaN
Name: ConvertedCompYearly, Length: 49191, dtype: float64

In [5]:
df['ConvertedCompYearly'].median()

75320.0

In [9]:
df.median()

TypeError: Cannot convert [['I am a developer by profession' 'I am a developer by profession'
  'I am a developer by profession' ... 'I am a developer by profession'
  'I am a developer by profession'
  'I am not primarily a developer, but I write code sometimes as part of my work/studies']
 ['25-34 years old' '25-34 years old' '35-44 years old' ...
  '35-44 years old' '25-34 years old' '18-24 years old']
 ['Master’s degree (M.A., M.S., M.Eng., MBA, etc.)'
  'Associate degree (A.A., A.S., etc.)'
  'Bachelor’s degree (B.A., B.S., B.Eng., etc.)' ...
  'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)'
  'Professional degree (JD, MD, Ph.D, Ed.D, etc.)'
  'Some college/university study without earning a degree']
 ...
 [nan nan nan ... nan nan nan]
 ['When I don’t trust AI’s answers'
  'When I don’t trust AI’s answers;When I want to fully understand something;When I want to learn best practices;When I want to compare different solutions;When I have ethical or security concerns about code'
  'When I don’t trust AI’s answers;When I want to fully understand something;When I want to learn best practices;When I have ethical or security concerns about code;When I’m stuck and can’t explain the problem'
  ... nan nan nan]
 ['Troubleshooting, profiling, debugging' 'All skills. AI is a flop.'
  'Understand how things actually work, problem solving, and algorithms'
  ... nan nan nan]] to numeric


# Error Troubleshooting

This error occurs because you're trying to calculate the median of a DataFrame that contains non-numeric data (strings, NaN values, etc.). The `median()` function only works on numeric data.

The error message shows that your DataFrame contains text data like "I am a developer by profession", age ranges like "25-34 years old", education levels like "Master's degree", and other categorical or text data.

In [10]:

# 2 approaches to solve the problem

# Option 1: Calculate median only for numeric columns
numeric_columns = df.select_dtypes(include=['number'])
numeric_medians = numeric_columns.median()

# Option 2: If you need to calculate something for categorical columns,
# you might need to use other methods like mode() for categorical data
categorical_columns = df.select_dtypes(exclude=['number'])
categorical_modes = categorical_columns.mode().iloc[0]  # Most frequent values

# Option 3: If you need to convert some specific columns to numeric first:
# For example, if you have age ranges and want to extract numeric values
# df['age_numeric'] = df['age_column'].str.extract('(\d+)').astype(float)
# Then calculate median
# df['age_numeric'].median()

In [12]:
# Option 1: Calculate median only for numeric columns
numeric_columns = df.select_dtypes(include=['number'])
numeric_medians = numeric_columns.median()

In [13]:
numeric_medians

ResponseId              24596.0
WorkExp                    10.0
YearsCode                  14.0
TechEndorse_1               9.0
TechEndorse_2               4.0
TechEndorse_3               4.0
TechEndorse_4               6.0
TechEndorse_5               4.0
TechEndorse_6               5.0
TechEndorse_7               7.0
TechEndorse_8               4.0
TechEndorse_9               4.0
TechEndorse_13             10.0
TechOppose_1                9.0
TechOppose_2                4.0
TechOppose_3                6.0
TechOppose_5                5.0
TechOppose_7                4.0
TechOppose_9                3.0
TechOppose_11               4.0
TechOppose_13               5.0
TechOppose_16               6.0
TechOppose_15              10.0
JobSatPoints_1              6.0
JobSatPoints_2              4.0
JobSatPoints_3              7.0
JobSatPoints_4             10.0
JobSatPoints_5             10.0
JobSatPoints_6              8.0
JobSatPoints_7              5.0
JobSatPoints_8              7.0
JobSatPoints_9              6.0
JobSatPoints_10             7.0
JobSatPoints_11             5.0
JobSatPoints_13             9.0
JobSatPoints_14             9.0
JobSatPoints_15            15.0
JobSatPoints_16             8.0
ToolCountWork               6.0
ToolCountPersonal           5.0
CompTotal              105000.0
SO_Actions_1                5.0
SO_Actions_16               2.0
SO_Actions_3                6.0
SO_Actions_4                4.0
SO_Actions_5                5.0
SO_Actions_6                5.0
SO_Actions_9                6.0
SO_Actions_7                5.0
SO_Actions_10               8.0
SO_Actions_15              10.0
ConvertedCompYearly     75320.0
JobSat                      8.0
dtype: float64

In [14]:
df.describe()

,ResponseId,WorkExp,YearsCode,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,ToolCountWork,ToolCountPersonal,CompTotal,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,ConvertedCompYearly,JobSat
count,49191.000000,42893.000000,43042.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,27611.000000,25582.000000,2.486600e+04,26260.000000,24340.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,2.394700e+04,26670.000000
mean,24596.000000,13.367403,16.570861,7.867352,4.104211,4.110271,5.678193,4.119388,5.225990,6.477387,4.370841,4.431661,9.854315,8.307948,4.524067,5.925567,4.991710,4.048980,3.799323,4.365831,5.059867,5.508538,9.945766,6.867738,5.216173,7.455719,9.537947,9.758209,8.194965,5.884096,7.367799,6.744658,7.512569,5.703283,8.563324,8.679349,14.687487,7.826685,17.734852,8.545579,2.234198e+70,4.907845,3.339770,5.718355,4.561767,4.790861,5.199657,5.676314,4.984653,7.099505,10.079284,1.017615e+05,7.201950
std,14200.362883,10.800117,11.787610,2.397432,2.275821,2.329536,2.398084,2.437945,2.801045,2.331468,2.357058,2.620901,1.975692,2.202164,2.282867,2.301937,2.294707,2.607443,2.499468,2.557152,2.533541,2.906146,2.087463,3.741490,3.660632,3.726759,3.781286,3.557588,3.801257,3.900813,4.118532,3.888845,3.847265,4.110528,3.545288,3.633175,1.898188,4.077460,269.810134,44.664738,3.523096e+72,2.682204,2.411404,2.628016,3.070548,2.643177,2.563562,2.310659,2.490095,2.469394,1.940928,4.617569e+05,1.997245
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,0.000000
25%,12298.500000,5.000000,8.000000,7.000000,2.000000,2.000000,4.000000,2.000000,3.000000,5.000000,2.000000,2.000000,10.000000,8.000000,3.000000,4.000000,3.000000,2.000000,2.000000,2.000000,3.000000,3.000000,10.000000,4.000000,2.000000,4.000000,7.000000,7.000000,5.000000,2.000000,4.000000,3.000000,4.000000,2.000000,6.000000,6.000000,15.000000,4.000000,4.000000,3.000000,5.500000e+04,3.000000,1.000000,3.000000,1.000000,3.000000,3.000000,4.000000,3.000000,6.000000,10.000000,3.817100e+04,6.000000
50%,24596.000000,10.000000,14.000000,9.000000,4.000000,4.000000,6.000000,4.000000,5.000000,7.000000,4.000000,4.000000,10.000000,9.000000,4.000000,6.000000,5.000000,4.000000,3.000000,4.000000,5.000000,6.000000,10.000000,6.000000,4.000000,7.000000,10.000000,10.000000,8.000000,5.000000,7.000000,6.000000,7.000000,5.000000,9.000000,9.000000,15.000000,8.000000,6.000000,5.000000,1.050000e+05,5.000000,2.000000,6.000000,4.000000,5.000000,5.000000,6.000000,5.000000,8.000000,10.000000,7.532000e+04,8.000000
75%,36893.500000,20.000000,24.000000,9.000000,6.000000,6.000000,8.000000,6.000000,8.000000,8.000000,6.000000,7.000000,10.000000,9.000000,6.000000,8.000000,7.000000,6.000000,6.000000,6.000000,7.000000,8.000000,10.000000,10.000000,8.000000,11.000000,13.000000,13.000000,11.000000,9.000000,11.000000,10.000000,11.000000,9.000000,12.000000,12.000000,15.000000,11.000000,10.000000,7.000000,2.400000e+05,7.000000,5.000000,8.000000,7.000000,7.000000,7.000000,7.000000,7.000000,9.000000,10.000000,1.205960e+05,8.000000
max,49191.000000,100.000000,100.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,14.000000,15.000000,15.000000,16.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,10000.000000,1000.000000,5.555556e+74,15.000000,10.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,5.000000e+07,10.000000

In [20]:
df['ConvertedCompYearly'].count()

np.int64(23947)

In [23]:
df['LearnCodeAI'].value_counts()

LearnCodeAI
Yes, I learned how to use AI-enabled tools required for my job or to benefit my career                                16403
Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies                                   14027
No, I learned something that was not related to AI or AI enablement for my personal curiosity and/or hobbies           5282
No, I didn't spend time learning in the past year                                                                      4864
No, I learned something that was not related to AI or AI enablement as required for my job or to benefit my career     4625
Name: count, dtype: int64

In [24]:

# to check whether a column presents in the dataframe

'SocialMedia' in df.columns

False

In [25]:
keywords = [
    "instagram", "reddit", "facebook",
    "twitter", "linkedin", "youtube", "tiktok"
]

In [26]:
import re

pattern = "|".join(keywords)

columns_with_social_media = (
    df.astype(str)
      .apply(lambda col: col.str.contains(pattern, case=False, na=False).any())
)

# Columns that contain social media values
social_media_columns = columns_with_social_media[columns_with_social_media].index.tolist()

social_media_columns

['TechEndorse_13_TEXT',
 'TechOppose_15_TEXT',
 'DevEnvHaveEntry',
 'OfficeStackHaveEntry',
 'CommPlatformHaveWorkedWith',
 'CommPlatformWantToWorkWith',
 'CommPlatformAdmired',
 'CommPlatformHaveEntr',
 'CommPlatformWantEntr',
 'AIExplain',
 'AIOpen']

In [27]:
matches = {}

for col in df.columns:
    found = (
        df[col].astype(str)
              .str.findall(pattern, flags=re.IGNORECASE)
              .explode()
              .dropna()
              .unique()
    )
    if len(found) > 0:
        matches[col] = list(found)

matches

{'TechEndorse_13_TEXT': ['youtube', 'Youtube', 'YouTube'],
 'TechOppose_15_TEXT': ['YouTube'],
 'DevEnvHaveEntry': ['twitter'],
 'OfficeStackHaveEntry': ['Facebook'],
 'CommPlatformHaveWorkedWith': ['Reddit', 'YouTube', 'LinkedIn'],
 'CommPlatformWantToWorkWith': ['Reddit', 'YouTube', 'LinkedIn'],
 'CommPlatformAdmired': ['Reddit', 'YouTube', 'LinkedIn'],
 'CommPlatformHaveEntr': ['Twitter',
  'Instagram',
  'YouTube',
  'facebook',
  'Facebook',
  'Linkedin',
  'Reddit',
  'youtube',
  'LinkedIn',
  'Youtube',
  'tiktok',
  'TikTok',
  'reddit',
  'linkedin'],
 'CommPlatformWantEntr': ['LinkedIn',
  'Instagram',
  'YouTube',
  'facebook',
  'Facebook',
  'Reddit',
  'youtube',
  'Twitter',
  'tiktok',
  'TikTok',
  'reddit',
  'linkedin'],
 'AIExplain': ['instagram',
  'youtube',
  'reddit',
  'Reddit',
  'YouTube',
  'TikTok',
  'Facebook',
  'Twitter',
  'twitter',
  'tiktok',
  'linkedin'],
 'AIOpen': ['YouTube', 'Facebook', 'reddit']}

In [30]:
df['CommPlatformWantToWorkWith']

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

0                                                      NaN
1        Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...
2         Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn
3        Stack Overflow;Reddit;GitHub (public projects,...
4        Stack Overflow;Stack Exchange;GitHub (public p...
                               ...
49186                                                  NaN
49187                                                  NaN
49188                                                  NaN
49189                                                  NaN
49190                                                  NaN
Name: CommPlatformWantToWorkWith, Length: 49191, dtype: object

In [29]:
schema_df.head(15)

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
5,QID18,TechEndorse_6,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
6,QID18,TechEndorse_7,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
7,QID18,TechEndorse_8,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
8,QID18,TechEndorse_9,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
9,QID18,TechEndorse_13,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
10,QID18,TechEndorse_13_TEXT,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
11,QID19,TechOppose_1,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
12,QID19,TechOppose_2,What would turn you off or cause you to reject...,RO,Poor usability,2.0
13,QID19,TechOppose_3,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
14,QID19,TechOppose_5,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0

In [39]:
schema_df

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
5,QID18,TechEndorse_6,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
6,QID18,TechEndorse_7,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
7,QID18,TechEndorse_8,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
8,QID18,TechEndorse_9,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
9,QID18,TechEndorse_13,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
10,QID18,TechEndorse_13_TEXT,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
11,QID19,TechOppose_1,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
12,QID19,TechOppose_2,What would turn you off or cause you to reject...,RO,Poor usability,2.0
13,QID19,TechOppose_3,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
14,QID19,TechOppose_5,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0
15,QID19,TechOppose_7,What would turn you off or cause you to reject...,RO,Prohibitive pricing,5.0
16,QID19,TechOppose_9,What would turn you off or cause you to reject...,RO,Security or privacy concerns,6.0
17,QID19,TechOppose_11,What would turn you off or cause you to reject...,RO,Availability of better alternatives,7.0
18,QID19,TechOppose_13,What would turn you off or cause you to reject...,RO,Outdated or obsolete technology or features,8.0
19,QID19,TechOppose_16,What would turn you off or cause you to reject...,RO,Ethical concerns,9.0
20,QID19,TechOppose_15,What would turn you off or cause you to reject...,RO,Other (please specify):,10.0
21,QID19,TechOppose_15_TEXT,What would turn you off or cause you to reject...,RO,Other (please specify): - Text,15.0
22,QID27,JobSatPoints_1,Rank the following attributes of your current ...,RO,Control over the level of quality in projects,1.0
23,QID27,JobSatPoints_2,Rank the following attributes of your current ...,RO,Autonomy and trust to manage your own tasks,2.0
24,QID27,JobSatPoints_16,Rank the following attributes of your current ...,RO,You like your manager,3.0
25,QID27,JobSatPoints_3,Rank the following attributes of your current ...,RO,Collaboration and support from a team,4.0
26,QID27,JobSatPoints_4,Rank the following attributes of your current ...,RO,Expert mentors,5.0
27,QID27,JobSatPoints_5,Rank the following attributes of your current ...,RO,Opportunities to mentor and lead junior-level ...,6.0
28,QID27,JobSatPoints_6,Rank the following attributes of your current ...,RO,Developing specialized expertise,7.0
29,QID27,JobSatPoints_7,Rank the following attributes of your current ...,RO,Solving real-world problems,8.0
30,QID27,JobSatPoints_8,Rank the following attributes of your current ...,RO,Job stability and career growth with a single ...,9.0
31,QID27,JobSatPoints_9,Rank the following attributes of your current ...,RO,Innovation through solving challenging and com...,10.0
32,QID27,JobSatPoints_10,Rank the following attributes of your current ...,RO,Working with new technologies and tools,11.0
33,QID27,JobSatPoints_11,Rank the following attributes of your current ...,RO,Competitive pay and benefits,12.0
34,QID27,JobSatPoints_13,Rank the following attributes of your current ...,RO,Recognition from peers for your work,13.0
35,QID27,JobSatPoints_14,Rank the following attributes of your current ...,RO,Recognition from leadership for your work,14.0
36,QID27,JobSatPoints_15,Rank the following attributes of your current ...,RO,Other (please specify):,15.0
37,QID27,JobSatPoints_15_TEXT,Rank the following attributes of your current ...,RO,Other (please specify): - Text,15.0
38,QID76,SO_Actions_1,"When visiting Stack Overflow, which following ...",RO,Browse content related to Q&A posts I recently...,1.0
39,QID76,SO_Actions_16,"When visiting Stack Overflow, which following ...",RO,Read and/or vote on comments for a Question or...,2.0
40,QID76,SO_Actions_3,"When visiting Stack Overflow, which following ...",RO,Bookmark posts to look at later,3.0
41,QID76,SO_Actions_4,"When visiting Stack Overflow, which following ...",RO,"Directly open a Q&A post via search, documenta...",4.0
42,QID76,SO_Actions_5,"When visiting Stack Overflow, which following ...",RO,Ask a question,5.0
43,QID76,SO_Actions_6,"When visiting Stack Overflow, which following ...",RO,Answer a question,6.0
44,QID76,SO_Actions_9,"When visiting Stack Overflow, which following ...",RO,Comment on Q&A posts,7.0
45,QID76,SO_Actions_7,"When visiting Stack Overflow, which following ...",RO,Upvote/Downvote Q&A posts,8.0
46,QID76,SO_Actions_10,"When visiting Stack Overflow, which following ...",RO,Use discussion or chat feature,9.0
47,QID76,SO_Actions_15,"When visiting Stack Overflow, which following ...",RO,Other (write in):,10.0
48,QID76,SO_Actions_15_TEXT,"When visiting Stack Overflow, which following ...",RO,Other (write in): - Text,15.0
49,QID3,MainBranch,Are you someone who writes code? Please select...,MC,NaN,NaN
50,QID4,Age,What is your age?,MC,NaN,NaN
51,QID9,EdLevel,Which of the following best describes the high...,MC,NaN,NaN
52,QID7,Employment,Which of the following best describes your cur...,MC,NaN,NaN
53,QID8,EmploymentAddl,Which of the following <strong>additional</str...,MC,NaN,NaN
54,QID14,WorkExp,How many years of professional work experience...,TE,NaN,NaN
55,QID10,LearnCodeChoose,Did you begin learning to code or learn a new ...,MC,NaN,NaN
56,QID11,LearnCode,How did you learn to code in the past year? Se...,MC,NaN,NaN
57,QID12,LearnCodeAI,Did you spend time in the last year learning A...,MC,NaN,NaN
58,QID32,AILearnHow,How did you learn to code for AI in the past y...,MC,NaN,NaN
59,QID13,YearsCode,"Including any education, how many years have y...",TE,NaN,NaN
60,QID15,DevType,Which of the following describes your current ...,MC,NaN,NaN
61,QID16,OrgSize,Approximately how many people are employed by ...,MC,NaN,NaN
62,QID23,ICorPM,Are you an individual contributor or people ma...,MC,NaN,NaN
63,QID24,RemoteWork,Which best describes your current work situation?,MC,NaN,NaN
64,QID17,PurchaseInfluence,Have you <strong>influenced or endorsed</stron...,MC,NaN,NaN
65,QID33,TechEndorseIntro,When you&rsquo;re in a position to <strong>inf...,MC,NaN,NaN
66,QID25,Industry,What industry do you work for in?,MC,NaN,NaN
67,QID26,JobSat,How satisfied are you in your current professi...,MC,NaN,NaN
68,QID28,AIThreat,Do you believe AI is a threat to your current ...,MC,NaN,NaN
69,QID29,NewRole,Have you considered a career change or transit...,MC,NaN,NaN
70,QID30,ToolCountWork,"For your <b>primary work role</b> (student, de...",TE,NaN,NaN
71,QID31,ToolCountPersonal,<b></b>For your <b>side projects or other pers...,TE,NaN,NaN
72,QID20,Country,Where do you live?,MC,NaN,NaN
73,QID21,Currency,Which currency do you use day-to-day? If your ...,MC,NaN,NaN
74,QID22,CompTotal,What is your current total <b>annual</b> compe...,TE,NaN,NaN
75,QID44,LanguageChoice,"Did you work with programming, scripting and m...",MC,NaN,NaN
76,QID34,Language,"Which <b>programming, scripting, and markup la...",Matrix,NaN,NaN
77,QID51,LanguagesHaveEntry,Was the programming language you use not liste...,TE,NaN,NaN
78,QID52,LanguagesWantEntry,Was the programming language you want to use n...,TE,NaN,NaN
79,QID45,DatabaseChoice,Did you work with database environments in the...,MC,NaN,NaN
80,QID35,Database,Which <b>database environments </b>have you do...,Matrix,NaN,NaN
81,QID54,DatabaseHaveEntry,Was the database environment you use not liste...,TE,NaN,NaN
82,QID55,DatabaseWantEntry,Was the database environment you want to use n...,TE,NaN,NaN
83,QID46,PlatformChoice,"Did you work with cloud platforms, containeriz...",MC,NaN,NaN
84,QID36,Platform,"Which <b>cloud platforms, containerization/orc...",Matrix,NaN,NaN
85,QID56,PlatformHaveEntry,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
86,QID57,PlatformWantEntry,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
87,QID47,WebframeChoice,Did you work with web frameworks and web techn...,MC,NaN,NaN
88,QID37,Webframe,Which <b>web frameworks and web technologies</...,Matrix,NaN,NaN
89,QID58,WebframeHaveEntry,Were the web frameworks and web technologies y...,TE,NaN,NaN
90,QID59,WebframeWantEntry,Were the web frameworks and web technologies y...,TE,NaN,NaN
91,QID48,DevEnvsChoice,Did you work with development environments or ...,MC,NaN,NaN
92,QID38,DevEnvs,Which <strong>development environments and AI-...,Matrix,NaN,NaN
93,QID60,DevEnvHaveEntry,Was the developer environment or AI-enabled co...,TE,NaN,NaN
94,QID61,DevEnvWantEntry,Was the developer environment or AI-enabled co...,TE,NaN,NaN
95,QID39,SOTags,Which rising technology of the added as <b>new...,Matrix,NaN,NaN
96,QID62,SOTagsHaveEntry,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
97,QID63,SOTagsWant Entry,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
98,QID40,OpSys,What is the primary <b>operating system</b> in...,Matrix,NaN,NaN
99,QID41,OfficeStackAsync,Which <b>collaborative work management and/or ...,Matrix,NaN,NaN
100,QID64,OfficeStackHaveEntry,Was the collaborative work management and/or c...,TE,NaN,NaN
101,QID65,OfficeStackWantEntry,Was the collaborative work management and/or c...,TE,NaN,NaN
102,QID42,CommPlatform,Which <b>community platforms</b> have you util...,Matrix,NaN,NaN
103,QID66,CommPlatformHaveEntr,Was the community platform you use not listed ...,TE,NaN,NaN
104,QID67,CommPlatformWantEntr,Was the community platform you want to use not...,TE,NaN,NaN
105,QID50,AIModelsChoice,Did you utilize or integrate specific Large La...,MC,NaN,NaN
106,QID43,AIModels,Which <b>LLM models for AI tools</b> have you ...,Matrix,NaN,NaN
107,QID68,AIModelsHaveEntry,Was the LLM model for AI tools you use not lis...,TE,NaN,NaN
108,QID69,AIModelsWantEntry,Was the LLM model for AI tools you want to use...,TE,NaN,NaN
109,QID72,SOAccount,Do you have a Stack Overflow account?,MC,NaN,NaN
110,QID70,SOVisitFreq,How frequently would you say you visit Stack O...,MC,NaN,NaN
111,QID71,SODuration,How long have you used Stack Overflow?,MC,NaN,NaN
112,QID73,SOPartFreq,How frequently would you say you participate i...,MC,NaN,NaN
113,QID75,SO_Dev_Content,"Whether it be to solve a problem, for career g...",MC,NaN,NaN
114,QID77,SOComm,Do you consider yourself a member of the Stack...,MC,NaN,NaN
115,QID97,SOFriction,"When you visit Stack Overflow, how often is it...",MC,NaN,NaN
116,QID78,AISelect,Do you currently use AI tools in your developm...,MC,NaN,NaN
117,QID79,AISent,How favorable is your stance on using AI tools...,MC,NaN,NaN
118,QID80,AIAcc,How much do you trust the accuracy of the outp...,MC,NaN,NaN
119,QID81,AIComplex,How well do the AI tools you use in your devel...,MC,NaN,NaN
120,QID82,AITool,Which parts of your development workflow are y...,Matrix,NaN,NaN
121,QID99,AIFrustration,"When using AI tools, which of the following pr...",MC,NaN,NaN
122,QID84,AIExplain,"In your own words, is &quot;vibe coding&quot; ...",TE,NaN,NaN
123,QID85,AIAgents,Are you using AI agents in your work (developm...,MC,NaN,NaN
124,QID83,AIAgentChange,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
125,QID86,AIAgent_Uses,What industry purposes or specific tasks are y...,MC,NaN,NaN
126,QID106,AgentUsesGeneral,,MC,NaN,NaN
127,QID87,AIAgentImpact,To what extent do you agree with the following...,Matrix,NaN,NaN
128,QID88,AIAgentChallenges,To what extent do you agree with the following...,Matrix,NaN,NaN
129,QID89,AIAgentKnowledge,You indicated you use or develop AI agents as ...,MC,NaN,NaN
130,QID107,AIAgentKnowWrite,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
131,QID90,AIAgentOrchestration,You indicated you use or develop AI agents as ...,MC,NaN,NaN
132,QID102,AIAgentOrchWrite,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
133,QID91,AIAgentObserveSecure,You indicated you use or develop AI agents as ...,MC,NaN,NaN
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [31]:
df['AIExplain']

0                     No
1                     No
2                     No
3                     NO
4                 partly
              ...
49186                NaN
49187                NaN
49188    Yes, partially.
49189                NaN
49190                NaN
Name: AIExplain, Length: 49191, dtype: object

In [33]:
'SocialMedia' in schema_df.columns

False

In [ ]:
# groupby

# 1. Split
# 2. Applying Function
# 3. Combine results

In [35]:
df['AIAgentExternal']

0                                                 ChatGPT
1                                                     NaN
2        ChatGPT;Claude Code;GitHub Copilot;Google Gemini
3                                     ChatGPT;Claude Code
4                                                     NaN
                               ...
49186                                                 NaN
49187                                                 NaN
49188                                                 NaN
49189                                                 NaN
49190                                                 NaN
Name: AIAgentExternal, Length: 49191, dtype: object

In [36]:
df['Country'].value_counts()

Country
United States of America                                7233
Germany                                                 3025
India                                                   2547
United Kingdom of Great Britain and Northern Ireland    2042
France                                                  1409
                                                        ...
Lesotho                                                    1
Djibouti                                                   1
Cape Verde                                                 1
Palau                                                      1
Guinea                                                     1
Name: count, Length: 177, dtype: int64

In [38]:
'AIAgentExternal' in schema_df.columns

False

In [42]:
schema_df.loc[135,'question']

'You indicated you use or develop AI agents as part of your development work.  Have you used any of the following out-of-the-box agents, copilots or assistants?'

In [43]:
schema_df.loc[135]

qid                                                     QID92
qname                                         AIAgentExternal
question    You indicated you use or develop AI agents as ...
type                                                       MC
sub                                                       NaN
sq_id                                                     NaN
Name: 135, dtype: object

In [44]:
df['EdLevel']

0          Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
1                      Associate degree (A.A., A.S., etc.)
2             Bachelor’s degree (B.A., B.S., B.Eng., etc.)
3             Bachelor’s degree (B.A., B.S., B.Eng., etc.)
4          Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
                               ...
49186         Bachelor’s degree (B.A., B.S., B.Eng., etc.)
49187    Some college/university study without earning ...
49188      Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
49189       Professional degree (JD, MD, Ph.D, Ed.D, etc.)
49190    Some college/university study without earning ...
Name: EdLevel, Length: 49191, dtype: object

In [45]:
df['EdLevel'].value_counts()

EdLevel
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          20278
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       12589
Some college/university study without earning a degree                                 6182
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     3631
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                         2624
Associate degree (A.A., A.S., etc.)                                                    1562
Other (please specify):                                                                 701
Primary/elementary school                                                               582
Name: count, dtype: int64

In [47]:
df['EdLevel'].value_counts(normalize = True)

EdLevel
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          0.421151
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       0.261459
Some college/university study without earning a degree                                0.128393
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    0.075412
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                        0.054497
Associate degree (A.A., A.S., etc.)                                                   0.032441
Other (please specify):                                                               0.014559
Primary/elementary school                                                             0.012087
Name: proportion, dtype: float64

In [48]:
df['Country'].value_counts()

Country
United States of America                                7233
Germany                                                 3025
India                                                   2547
United Kingdom of Great Britain and Northern Ireland    2042
France                                                  1409
                                                        ...
Lesotho                                                    1
Djibouti                                                   1
Cape Verde                                                 1
Palau                                                      1
Guinea                                                     1
Name: count, Length: 177, dtype: int64

In [49]:
df.groupby(['Country'])

In [4]:
country_grp = df.groupby(['Country'])

In [51]:
country_grp.get_group('United States of America')

/var/folders/55/d6806_zn1l39xvg_qlwf_tn00000gn/T/ipykernel_1085/636347133.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  country_grp.get_group('United States of America')

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
21,22,"I am not primarily a developer, but I write co...",45-54 years old,Some college/university study without earning ...,Employed,None of the above,35.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I didn't spend time learning in the past year",NaN,35.0,Academic researcher,I don’t know,People manager,"Your choice (very flexible, you can come in wh...",No,Work,12.0,13.0,9.0,10.0,4.0,11.0,8.0,7.0,3.0,14.0,NaN,15.0,12.0,13.0,4.0,8.0,1.0,2.0,7.0,9.0,14.0,NaN,Higher Education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have somewhat considered changing my career ...,NaN,NaN,United States of America,USD United States dollar,NaN,Yes,Assembly;Bash/Shell (all shells);C;C++;Fortran...,C++;Python;Gleam,C++;Python,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Jupyter Notebook/JupyterLab;Neovim;Vim,Neovim,Neovim,Emacs,Emacs,c++23,c++23,c++23,NaN,NaN,MacOS;Linux (non-WSL),MacOS;Linux (non-WSL),Doxygen;GitHub,NaN,NaN,NaN,NaN,"GitHub (public projects, not private repos)",NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Less than once per month or monthly,Between 5 and 10 years,Less than once every 2 - 3 months,NaN,3.0,NaN,15.0,1.0,6.0,14.0,5.0,4.0,7.0,2.0,NaN,"No, not at all",I don't use AI or AI-enabled tools,"No, and I don't plan to",Very unfavorable,Highly distrust,I don't use AI tools for complex tasks / I don...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,I don’t use AI tools regularly,no,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,interacting with people,NaN,NaN
22,23,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Colleague or on-the-job training,11.0,"Developer, full-stack",100 to 499 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,13.0,3.0,9.0,10.0,1.0,11.0,4.0,2.0,5.0,14.0,NaN,14.0,2.0,8.0,12.0,4.0,1.0,13.0,10.0,3.0,15.0,NaN,Fintech,3.0,2.0,4.0,6.0,9.0,10.0,5.0,11.0,8.0,12.0,1.0,13.0,14.0,15.0,7.0,NaN,I'm not sure,I have somewhat considered changing my career ...,5.0,10.0,United States of America,USD United States dollar,87500.0,Yes,C#;C++;JavaScript;Python;Visual Basic (.Net),C#;Python,C#;Python,NaN,NaN,Yes,Microsoft SQL Server,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud;Microso...,Microsoft Azure,Microsoft Azure,NaN,NaN,Yes,ASP.NET;ASP.NET Core;jQuery,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,NaN,NaN,Yes,Notepad++;PyCharm;Visual Studio;Visual Studio ...,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Windows,Azure Devops;GitHub;Obsidian;Stack Overflow fo...,Azure Devops;GitHub;Obsidian,Azure Devops;GitHub;Obsidian,NaN,NaN,Stack Overflow;Stack Exchange;Discord;Reddit;H...,Stack Overflow;Stack Exchange;Discord;Reddit;H...,Stack Overflow;Stack Exchange;Discord;Reddit;H...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,Less than once every 2 - 3 months,"Lists of recommendations (tools, frameworks, t...",4.0,NaN,8.0,1.0,12.0,11.0,10.0,2.0,9.0,15.0,NaN,"Yes, definitely","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Unfavorable,Somewhat distrust,Bad at handling complex tasks,Writing code,Learning about a codebase;Project planning;Doc...,Debugging or fixing code;Creating or maintaini...,Predictive analytics,NaN,"AI solutions that are almost right, but not qu...","No. I find it to be useless, unless I'm starti...","No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,NaN,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Technical knowledge. As AI slides into the for...,87500.0,9.0
29,30,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (10-19 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,15.0,"Developer, mobile",500 to 999 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,9.0,3.0,4.0,8.0,11.0,7.0,5.0,1.0,10.0,14.0,NaN,12.0,4.0,5.0,9.0,14.0,7.0,11.0,6.0,2.0,15.0,NaN,Software Development,7.0,6.0,9.0,10.0,11.0,12.0,13.0,5.0,14.0,8.0,1.0,3.0,4.0,15.0,2.0,NaN,No,I have neither consider or transitioned into a...,6.0,6.0,United States of America,USD United States dollar,205000.0,Yes,Bash/Shell (all shells);C;C#;C++;Java;JavaScri...,NaN,NaN,NaN,NaN,Yes,MySQL;PostgreSQL;SQLite;Supabase,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Digital O...,NaN,NaN,NaN,NaN,Yes,Next.js;Node.js;React,NaN,NaN,"Remix, Capacitor, Ionic",NaN,Yes,Android Studio;Claude Code;Cursor;IntelliJ IDE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;Linux (non-WSL),Windows;MacOS;Android;Linux (non-WSL),GitHub;GitLab;Google Workspace;Jira;Notion;Tre...,NaN,NaN,NaN,NaN,Discord;Reddit;Hacker News;GitHub (public proj...,NaN,NaN,NaN,NaN,Yes,Anthropic: Claude Sonnet;openAI Reasoning models,NaN,NaN,NaN,NaN,Yes,Less than once per month or monthly,Between 10 and 15 years,"Infrequently, less than once per year",Chat (bot/AI),10.0,NaN,9.0,6.0,1.0,5.0,13.0,12.0,8.0,15.0,NaN,"No, not really",About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat distrust,Very poor at handling complex tasks,Writing code;Learning new concepts or technolo...,Project planning;Deployment and monitoring;Pre...,Learning about a codebase;Testing code,Committing and reviewing code;Creating or main...,Documenting code;Debugging or fixing code;Sear...,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,NaN,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Being able to make sure the AI code is correct...,205000.0,8.0
31,32,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,17.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",NaN,23.0,"Developer, full-stack",100 to 499 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,13.0,3.0,6.0,11.0,10.0,9.0,8.0,2.0,1.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fintech,2.0,3.0,4.0,11.0,12.0,5.0,6.0,10.0,7.0,8.0,9.0,13.0,14.0,15.0,1.0,NaN,No,I have neither consider or transitioned into a...,5.0,8.0,United States of America,USD United States dollar,250000.0,Yes,Elixir;HTML/CSS;JavaScript;SQL;TypeScript,Elixir;HTML/CSS;OCaml;Gleam,Elixir;HTML/CSS,NaN,NaN,Yes,BigQuery;Elasticsearch;PostgreSQL;SQLite,SQLite,SQLite,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Datadog;D...,Cloudflare;Homebrew;Make,Cloudflare;Homebrew;Make,hex,hex,Yes,Node.js;Phoenix;React,Phoenix,Phoenix,NaN,NaN,Yes,NaN,NaN,NaN,emacs,emacs,Tailwind CSS 4;Large Language Model,Tailwind CSS 4,Tailwind CSS 4,NaN,NaN,MacOS,MacOS,Airtable;Confluence;GitHub;Google Workspace;Ji...,NaN,NaN,NaN,NaN,Reddit;Dev.to;Hacker News;GitHub (public proje...,"GitHub (public projects, not private repos);Sl...","GitHub (public projects, not private repos);Sl...",NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,I have never participated in Q&A on Stack Over...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No, not at all",I don't use AI or AI-enabled tools,"No, and I don't plan to",Very unfavorable,Highly distrust,I don't use AI tools for complex tasks / I don...,NaN,NaN,NaN,NaN,NaN,I don’t use AI tools regularly,no,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,250000.0,8.0
33,34,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,24.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"No, I didn't spend time learning in the past year",NaN,26.0,Data engineer,"5,000 to 9,999 employees",Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I influenced the purchase of a substantia...",Work,10.0,5.0,4.0,7.0,2.0,11.0,8.0,3.0,1.0,14.0,NaN,12.0,2.0,5.0,1.0,9.0,8.0,3.0,4.0,14.0,15.0,NaN,Software Development,3.0,4.0,11.0,14.0,13.0,8.0,12.0,1.0,6.0,7.0,2.0,9.0,10.0,15.0,5.0,NaN,No,I have neither consider or transitioned into a...,3.0,0.0,United States of America,USD United States dollar,175000.0,Yes,C#;Python;SQL,NaN,NaN,NaN,NaN,Yes,Microsoft SQL Server,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Microsoft Azure;Terr...,NaN,NaN,NaN,NaN,Yes,ASP.NET;ASP.NET Core,NaN,NaN,NaN,NaN,Yes,Visual Studio;Visual Studio Code,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Windows Subsystem for Linux (WSL);Linu...,Azure Devops;Jira,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 10 and 15 years,A few times per month or weekly,NaN,6.0,NaN,8.0,12.0,7.0,4.0,5.0,2.0,10.0,15.0,NaN,"Yes, somewhat","Rarely, almost never","No, and I don't plan to",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,I don’t use AI tools regularly,no,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,business logic,175000.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49125,49126,I work with developers or my work supports dev...,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,5.0,Cybersecurity or InfoSec professional,100 to 499 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,10.0,3.0,2.0,8.0,1.0,5.0,4.0,7.0,6.0,9.0,NaN,9.0,10.0,2.0,8.0,7.0,1.0,6.0,4.0,5.0,3.0,AI integration required,Fintech,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have somewhat considered changing my career ...,10.0,3.0,United States of America,USD United States dollar,100000.0,Yes,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Assembly;C;GDScript;Go;Lua;MicroPython;Python;...,Go;Lua;MicroPython;Python,Nu,Nu,Yes,Cosmos DB;Databricks SQL;Microsoft SQL Server;...,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,Yes,Amazon Web Services (AWS);Ansible;Cargo;Cloudf...,Cargo;Homebrew;Make;Pip;Poetry,Cargo;Homebrew;Pip;Poetry,"uv,pipx","uv,pipx",Yes,Angular;Spring Boot;WordPress,NaN,NaN,JSP,NaN,Yes,Cursor;IntelliJ IDEA;Jupyter Notebook/JupyterL...,Jupyter Notebook/JupyterLab;Neovim,Jupyter Notebook/JupyterLab;Neovim,NaN,NaN,Large Language Model;RAG;Ollama;uv;visionOS,Pydantic;uv;visionOS,uv;visionOS,NaN,NaN,MacOS;Ubuntu;iOS;Linux (non-WSL);Arch;iPadOS,Windows;MacOS;Ubuntu;Linux (non-WSL),Airtable;Confluence;GitHub;Jira;Markdown File;...,GitHub;Markdown File;Obsidian;Wikis,GitHub;Markdown File;Obsidian;Wikis,NaN,NaN,Stack Overflow;Stack Exchange;Discord;Hacker N...,Bluesky;YouTube,Bluesky;YouTube,Matrix,Matrix,Yes,Anthropic: Claude Sonnet;Meta Llama (all model...,NaN,NaN,NaN,NaN,Not sure/can't remember,Less than once per month or monthly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Long-form articles;Coding challenges;Logic gam...,3.0,6.0,7.0,4.0,2.0,1.0,8.0,5.0,9.0,10.0,NaN,"No, not really",About half of the time,"Yes, I use AI tools weekly",Unfavorable,Highly distrust,Very poor at handling complex tasks,Writing code;Debugging or fixing code;Search f...,Learning about a codebase;Testing code;Committ...,Documenting code;Predictive analytics;Creating...,Generating content or synthetic data,Project planning,"AI solutions that are almost right, but not qu...","No, though we have been encouraged to and the ...","No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,"Literacy, Numeracy, Critical Reasoning, and No...",NaN,NaN
49127,49128,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),6.0,"Yes, I am not new to coding but am learning ne...","School (i.e., University, College, etc)","Yes, I learned how to use AI-enabled tools for...","Other online resources (e.g. standard search, ...",6.0,"Developer, full-stack","1,000 to 4,999 employees",Individual contributor,Remote,"Yes, I influenced the purchase of a substantia...",Work,5.0,7.0,3.0,9.0,6.0,4.0,1.0,8.0,2.0,10.0,NaN,5.0,3.0,1.0,4.0,2.0,9.0,8.0,7.0,6.0,10.0,NaN,Energy,9.0,4.0,7.0,3.0,8.0,11.0,1.0,6.0,10.0,2.0,13.0,14.0,12.0,15.0,5.0,NaN,Yes,I have somewhat considered changing my career ...,10.0,10.0,United States of America,USD United States dollar,200000.0,Yes,Bash/Shell (all shells);C;Go;Java;JavaScript;P...,NaN,NaN,NaN,NaN,Yes,Dynamodb;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Docker;Kubernetes,NaN,NaN,NaN,NaN,Yes,jQuery;Next.js;Node.js;React;Spring Boot,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Google Gemini,NaN,NaN,NaN,NaN,Windows;MacOS;Windows Subsystem for Linux (WSL),NaN,Jira,NaN,NaN,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,Gemini (Pro Reasoning models),NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Somewhat trust,Neither good or bad at handling complex tasks,NaN,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, but I plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,The cost of using certain AI agent platforms i...,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something;When...,NaN,NaN,10.0

In [52]:
filt = df['Country'] == 'United States of America'
df.loc[filt]['EdLevel'].value_counts()

21       Some college/university study without earning ...
22       Some college/university study without earning ...
29         Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
31            Bachelor’s degree (B.A., B.S., B.Eng., etc.)
33            Bachelor’s degree (B.A., B.S., B.Eng., etc.)
                               ...
49125         Bachelor’s degree (B.A., B.S., B.Eng., etc.)
49127         Bachelor’s degree (B.A., B.S., B.Eng., etc.)
49145      Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
49157         Bachelor’s degree (B.A., B.S., B.Eng., etc.)
49177         Bachelor’s degree (B.A., B.S., B.Eng., etc.)
Name: EdLevel, Length: 7233, dtype: object

In [53]:
df.loc[filt]['EdLevel'].value_counts()

EdLevel
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          3607
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       1447
Some college/university study without earning a degree                                 976
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                         419
Associate degree (A.A., A.S., etc.)                                                    335
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     313
Primary/elementary school                                                               57
Other (please specify):                                                                 56
Name: count, dtype: int64

In [54]:
filt = df['Country'] == 'India'
df.loc[filt]['EdLevel'].value_counts()

EdLevel
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          1614
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        534
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     154
Some college/university study without earning a degree                                 149
Other (please specify):                                                                 49
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                          23
Primary/elementary school                                                               17
Associate degree (A.A., A.S., etc.)                                                      3
Name: count, dtype: int64

In [55]:
country_grp['EdLevel'].value_counts()

Country      EdLevel
Afghanistan  Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          5
             Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       2
             Primary/elementary school                                                             1
             Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                        1
             Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    1
                                                                                                  ..
Zambia       Primary/elementary school                                                             1
             Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    1
Zimbabwe     Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          7
             Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       4
             Some college/university study without earning a degree                                2
Name: count, Length: 903, dtype: int64

In [56]:
country_grp['EdLevel'].value_counts().head(20)

Country      EdLevel
Afghanistan  Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                           5
             Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        2
             Primary/elementary school                                                              1
             Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                         1
             Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     1
             Some college/university study without earning a degree                                 1
Albania      Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                           8
             Some college/university study without earning a degree                                 5
             Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        3
             Primary/elementary school                                                              2
             Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     2
             Associate degree (A.A., A.S., etc.)                                                    1
             Other (please specify):                                                                1
Algeria      Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       21
             Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          12
             Some college/university study without earning a degree                                 7
             Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                         4
             Other (please specify):                                                                2
             Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     2
Andorra      Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        3
Name: count, dtype: int64

In [57]:
country_grp['EdLevel'].value_counts().loc['India']

EdLevel
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          1614
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        534
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     154
Some college/university study without earning a degree                                 149
Other (please specify):                                                                 49
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                          23
Primary/elementary school                                                               17
Associate degree (A.A., A.S., etc.)                                                      3
Name: count, dtype: int64

In [58]:
country_grp['EdLevel'].value_counts().loc['Germany']

EdLevel
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       1087
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                           769
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     422
Some college/university study without earning a degree                                 344
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                         243
Associate degree (A.A., A.S., etc.)                                                     74
Other (please specify):                                                                 60
Primary/elementary school                                                               18
Name: count, dtype: int64

In [59]:
country_grp['EdLevel'].value_counts().loc['China']

EdLevel
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          131
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        51
Some college/university study without earning a degree                                 35
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     22
Associate degree (A.A., A.S., etc.)                                                     6
Primary/elementary school                                                               6
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                          3
Other (please specify):                                                                 1
Name: count, dtype: int64

In [63]:
country_grp['EdLevel'].value_counts().loc['United Kingdom of Great Britain and Northern Ireland']

EdLevel
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          913
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       498
Some college/university study without earning a degree                                294
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                        173
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    110
Associate degree (A.A., A.S., etc.)                                                    30
Other (please specify):                                                                16
Primary/elementary school                                                               4
Name: count, dtype: int64

In [62]:
df['Country'].head(56)

0                                               Ukraine
1                                           Netherlands
2                                               Ukraine
3                                               Ukraine
4                                               Ukraine
5                                               Ukraine
6                                               Ukraine
7                                               Ukraine
8                                               Ukraine
9                                               Ukraine
10                                              Ukraine
11                                              Ukraine
12                                              Ukraine
13                                                India
14                                              Georgia
15                                                India
16                                            Australia
17                                               Greece
18                                              Germany
19                                           Bangladesh
20                                               Brazil
21                             United States of America
22                             United States of America
23                                          Netherlands
24                                            Lithuania
25    United Kingdom of Great Britain and Northern I...
26                                              Ireland
27                                               Sweden
28                                   Dominican Republic
29                             United States of America
30                                              Austria
31                             United States of America
32                                              Belgium
33                             United States of America
34                                       Czech Republic
35                                              Germany
36                                                Italy
37                             United States of America
38    United Kingdom of Great Britain and Northern I...
39                             United States of America
40                             United States of America
41                             United States of America
42                             United States of America
43                                       Czech Republic
44                                       Czech Republic
45                                              Hungary
46                                                India
47                                             Malaysia
48    United Kingdom of Great Britain and Northern I...
49                                          Switzerland
50                                              Germany
51                                          Netherlands
52                                                Egypt
53                             United States of America
54                                          Netherlands
55                                              Austria
Name: Country, dtype: object

In [15]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=172)

In [8]:
country_grp['ConvertedCompYearly'].median()

Country
Afghanistan                               6121.0
Albania                                  26269.0
Algeria                                   6472.0
Andorra                                 200125.5
Angola                                    9578.0
                                          ...
Venezuela, Bolivarian Republic of...      9000.0
Viet Nam                                  7642.0
Yemen                                     5545.5
Zambia                                    1966.5
Zimbabwe                                 17500.0
Name: ConvertedCompYearly, Length: 177, dtype: float64

In [11]:
country_grp['ConvertedCompYearly'].median().loc['Germany']

np.float64(81210.0)

In [12]:
country_grp['ConvertedCompYearly'].median().loc['India']

np.float64(17029.0)

In [13]:
country_grp['ConvertedCompYearly'].agg(['median', 'mean'])

                                        median           mean
Country
Afghanistan                             6121.0   12227.250000
Albania                                26269.0   47973.583333
Algeria                                 6472.0   15935.400000
Andorra                               200125.5  208763.750000
Angola                                  9578.0  149857.250000
...                                        ...            ...
Venezuela, Bolivarian Republic of...    9000.0   17008.400000
Viet Nam                                7642.0  189894.192982
Yemen                                   5545.5   17582.500000
Zambia                                  1966.5    6594.875000
Zimbabwe                               17500.0   25662.500000

[177 rows x 2 columns]

In [14]:
country_grp['ConvertedCompYearly'].agg(['median', 'mean']).loc['India']

median    17029.000000
mean      44291.789234
Name: India, dtype: float64

In [16]:
df['LanguageHaveWorkedWith']

0                         Bash/Shell (all shells);Dart;SQL
1                                                     Java
2                      Dart;HTML/CSS;JavaScript;TypeScript
3                                          Java;Kotlin;SQL
4        C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
                               ...
49186                                                  NaN
49187                                                  NaN
49188                                                  NaN
49189                                                  NaN
49190                                                  NaN
Name: LanguageHaveWorkedWith, Length: 49191, dtype: object

In [17]:
filt = df['Country'] == 'India'

In [18]:
df.loc[filt]

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
13,14,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Other onli...,6.0,"Developer, full-stack","1,000 to 4,999 employees",People manager,In-person,"Yes, I influenced the purchase of a substantia...",NaN,9.0,2.0,8.0,13.0,11.0,6.0,3.0,10.0,5.0,14.0,NaN,3.0,8.0,5.0,13.0,14.0,10.0,2.0,7.0,6.0,15.0,NaN,Fintech,8.0,10.0,12.0,9.0,3.0,7.0,1.0,2.0,5.0,4.0,6.0,11.0,13.0,15.0,14.0,NaN,No,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Less than once every 2 - 3 months,Less than one year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
15,16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,3.0,"Developer, mobile",20 to 99 employees,Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,9.0,3.0,6.0,7.0,2.0,8.0,1.0,4.0,5.0,14.0,NaN,7.0,4.0,8.0,14.0,5.0,12.0,3.0,13.0,9.0,15.0,NaN,Software Development,1.0,2.0,5.0,4.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,Yes,I have somewhat considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...,Ada;Bash/Shell (all shells);C;C#;C++;Rust;Scal...,Ada;C;C#;C++;Rust;Scala;SQL,5,1,Yes,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;I...,Dynamodb;InfluxDB,InfluxDB,5,4,Yes,Amazon Web Services (AWS);APT;Bun;Chocolatey;D...,Ansible;Cargo;Cloudflare;Composer;Firebase;Goo...,Pip,5,4,Yes,Angular;AngularJS;ASP.NET;ASP.NET Core;Astro;B...,Drupal;Fastify;NestJS;Next.js;Node.js;Nuxt.js;...,Drupal;React,4,4,No,NaN,NaN,NaN,NaN,NaN,c++23;Amazon Bedrock;Microsoft Fabric;Google G...,NaN,NaN,5,4,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Airtable;Asana;Azure Devops;Clickup;Coda;Confl...,Notion;Obsidian,Notion;Obsidian,4,5,Stack Overflow;Stack Exchange;Discord;Reddit;D...,NaN,NaN,5,5,Yes,Alibaba Cloud Qwen models;Amazon Titan models;...,NaN,NaN,NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,Less than once every 2 - 3 months,Message Boards;Videos;Coding challenges;Logic ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Favorable,Highly trust,"Good, but not great at handling complex tasks",Search for answers,NaN,NaN,Documenting code,Learning about a codebase;Project planning;Wri...,"AI solutions that are almost right, but not qu...",NaN,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering;Business process automati...,Language processing;Agent/multi-agent orchestr...,NaN,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,NaN,Fireproof;LanceDB;Letta;Neo4j;Qdrant,NaN,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,NaN,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,NaN,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,NaN,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
46,47,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Volunteering (regularly),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,NaN,"Developer, embedded applications or devices","10,000 or more employees",Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,Bash/Shell (all shells);Go;Groovy;HTML/CSS;Jav...,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,NaN,NaN,Yes,Cassandra;Elasticsearch,Cassandra;Elasticsearch,Cassandra;Elasticsearch,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
90,91,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,6.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was open-source an...",Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,50.0,Yes,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,"Javascript,php,node,react,jQuery,MySQL,",NaN,Yes,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,NaN,NaN,Yes,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,NaN,NaN,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,NaN,NaN,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,NaN,NaN,Yes,Less than once every 2 - 3 months,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Long-form articles;Videos;Coding challenges;Di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",Less than half of the time,NaN,Very favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software engineering;Cybersecurity,Language processing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,7.0
133,134,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,10.0,"Developer, full-stack","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,10.0,1.0,3.0,5.0,9.0,13.0,6.0,2.0,4.0,14.0,NaN,9.0,3.0,11.0,6.0,7.0,2.0,4.0,12.0,1.0,15.0,NaN,"Transportation, or Supply Chain",2.0,3.0,6.0,7.0,10.0,11.0,1.0,9.0,12.0,14.0,8.0,13.0,4.0,15.0,5.0,All are there in my case are and are at equal ...,Yes,I have transitioned into a new career and/or i...,5.0,2.0,India,INR Indian rupee,1730000.0,Yes,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;PowerShell;TypeScript,HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,Microsoft SQL Server;MySQL;PostgreSQL,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL,Microsoft SQL Server;MySQL;PostgreSQL,NaN,NaN,Yes,npm,npm,npm,Azure,Azure,Yes,jQuery,NaN,NaN,NaN,NaN,Yes,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS,Windows,GitHub;Markdown File;Notion,GitHub;Markdown File,GitHub;Markdown File,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;GitHub (p...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,A few times per week,Chat (people);Message Boards;Long-form article...,13.0,NaN,3.0,11.0,2.0,1.0,8.0,4.0,14.0,15.0,NaN,"Yes, definitely","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Favorable,Somewhat distrust,Very poor at handling complex tasks,Search for answers;Learning new concepts or te...,Writing code;Debugging or fixing code;Testing ...,Learning about a codebase;Project planning;Doc...,Creating or maintaining documentation,NaN,Debugging AI-generated code is more time-consu...,Nope,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,AI agents have accelerated my learning about n...,NaN,NaN,AI agents have improved the quality of my code...,NaN,NaN,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,AutoGen (Microsoft),NaN,NaN,NaN,ChatGPT;Google Gemini;Microsoft Copilot,NaN,When I have ethical or security concerns about...,Problem solving,20109.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49132,49133,I code primarily as a hobby,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Not employed,NaN,NaN,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Videos (not associated ...,"No, I learned something that was not related t...",NaN,3.0,Student,NaN,NaN,NaN,NaN,Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have neither consider or transitioned into a...,NaN,2.0,India,INR Indian rupee,NaN,Yes,HTML/CSS;Java;JavaScript;Python;Rust;TypeScript,Rust;TypeScript,Rust;TypeScript,NaN,NaN,Yes,MySQL;Redis;SQLite,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Ansible;Homebrew;Kub...,Kubernetes;npm,Kubernetes;npm,NaN,NaN,Yes,Node.js;React;Axum,Next.js;React;Axum,React;Axum,NaN,NaN,NaN,Cursor;Visual Studio Code,Cursor,Cursor,NaN,NaN,Tailwind CSS 4,Tailwind CSS 4,Tailwind CSS 4,NaN,NaN,MacOS,MacOS,NaN,NaN,NaN,NaN,NaN,Stack Overflow;YouTube,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Less than once per month or monthly,Less than one year,Less than once every 2 - 3 months,Chat (people),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No, not really",NaN,"Yes, I use AI tools daily",Favorable,Somewhat trust,Very well at handling complex tasks,NaN,Project planning;Generating content or synthet...,Learning about a codebase;Writing code;Documen...,Debugging or fixing code;Testing code;Committi...,Search for answers,I’ve become less confident in my own problem-s...,NaN,"No, but I plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I’m stuck and can’t explain the problem,Maths,NaN,NaN
49141,49142,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,1.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,5.0,Data engineer,20 to 99 employees,NaN,In-person,"Yes, I influenced the purchase of a substantia...",Work,4.0,6.0,1.0,3.0,5.0,2.0,8.0,9.0,7.0,10.0,NaN,7.0,6.0,2.0,1.0,8.0,9.0,5.0,3.0,4.0,10.0,NaN,Software Development,13.0,10.0,6.0,1.0,4.0,9.0,5.0,14.0,2.0,12.0,7.0,8.0,3.0,15.0,11.0,NaN,Yes,I have strongly considered changing my career ...,10.0,4.0,India,INR Indian rupee,750000.0,Yes,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Java;JavaScript;Python,Java;JavaScript;Python,PySpark,NaN,Yes,Databricks SQL;Dynamodb;MySQL;Snowflake;Amazon...,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Docker;Kubernetes;Te...,Amazon Web Services (AWS);Docker;Kubernetes;Te...,Amazon Web Services (AWS);Docker;Kubernetes;Te...,NaN,NaN,Yes,Express;Node.js,Express;Node.js;Spring Boot,Express;Node.js,NaN,NaN,Yes,Claude Code;Jupyter Notebook/JupyterLab;Visual...,Claude Code;Jupyter Notebook/JupyterLab;Visual...,Claude Code;Jupyter Notebook/JupyterLab;Visual...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;Ubuntu,Windows;Ubuntu,GitHub;GitLab,GitHub;GitLab,GitHub;GitLab,NaN,NaN,Stack Overflow;YouTube;LinkedIn;Medium,Stack Overflow;YouTube;LinkedIn;Medium,Stack Overflow;YouTube;LinkedIn;Medium,NaN,NaN,Yes,Gemini (Pro Reasoning models);openAI GPT (chat...,Gemini (Pro Reasoning models);openAI GPT (chat...,Gemini (Pro Reasoning models);openAI GPT (chat...,NaN,NaN,Yes,Daily or almost daily,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,Job board,3.0,5.0,9.0,6.0,4.0,7.0,2.0,8.0,1.0,10.0,NaN,"Yes, definitely",Less than half of the time,"Yes, I use AI tools daily",Very favorable,Highly trust,Very well at handling complex tasks,NaN,NaN,NaN,Learning about a codebase;Project planning;Wri...,NaN,"AI solutions that are almost right, but not quite",NaN,NaN,"Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
49149,49150,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (less than 10 hours per w...,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,10.0,"Developer, front-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,4.0,5.0,6.0,3.0,8.0,1.0,9.0,2.0,7.0,10.0,NaN,7.0,9.0,4.0,2.0,6.0,5.0,1.0,3.0,8.0,10.0,NaN,Software Development,6.0,12.0,4.0,9.0,7.0,11.0,3.0,14.0,13.0,5.0,2.0,1.0,8.0,15.0,10.0,NaN,Yes,I have transitioned into a new career and/or i...,NaN,NaN,India,INR Indian rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools daily",Very favorable,Neither trust nor distrust,Neither good or bad at handling complex tasks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0

In [21]:
df.loc[filt]['LanguageHaveWorkedWith'].str.contains('Python')

13         NaN
15        True
46        True
90        True
133      False
         ...
49132     True
49141     True
49149      NaN
49154      NaN
49155      NaN
Name: LanguageHaveWorkedWith, Length: 2547, dtype: object

In [22]:
df.loc[filt]['LanguageHaveWorkedWith'].str.contains('Python').sum()

1162

In [24]:
country_grp['LanguageHaveWorkedWith'].str.contains('Python').sum()

AttributeError: 'SeriesGroupBy' object has no attribute 'str'


# Convert GroupBy object back to DataFrame

country_filtered = country_grp.reset_index() 
country_filtered['contains_python'] = country_filtered['LanguageHaveWorkedWith'].str.contains('Python')
result = country_filtered.groupby('country')['contains_python'].sum()

# Option 2: If you need to apply the operation within each group
# Use apply to access the string methods within each group

cess the string methods within each group
result = country_grp.apply(lambda x: x['LanguageHaveWorkedWith'].str.contains('Python').sum())

In [25]:
country_grp['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              4
Albania                                 10
Algeria                                 23
Andorra                                  2
Angola                                   1
                                        ..
Venezuela, Bolivarian Republic of...    23
Viet Nam                                78
Yemen                                    6
Zambia                                   7
Zimbabwe                                 7
Name: LanguageHaveWorkedWith, Length: 177, dtype: int64

In [26]:
country_grp['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum()).loc['India']

np.int64(1162)

In [28]:



country_grp['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').value_counts(normalize=True))

Country
Afghanistan  False    0.555556
             True     0.444444
Albania      False    0.523810
             True     0.476190
Algeria      True     0.638889
                        ...
Yemen        False    0.500000
Zambia       True     0.700000
             False    0.300000
Zimbabwe     True     0.636364
             False    0.363636
Name: LanguageHaveWorkedWith, Length: 325, dtype: float64

In [35]:
country_respondents = df['Country'].value_counts()
country_respondents

Country
United States of America                                7233
Germany                                                 3025
India                                                   2547
United Kingdom of Great Britain and Northern Ireland    2042
France                                                  1409
                                                        ...
Lesotho                                                    1
Djibouti                                                   1
Cape Verde                                                 1
Palau                                                      1
Guinea                                                     1
Name: count, Length: 177, dtype: int64

In [33]:
persons_in_country_uses_python = country_grp['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

In [34]:
persons_in_country_uses_python

Country
Afghanistan                              4
Albania                                 10
Algeria                                 23
Andorra                                  2
Angola                                   1
                                        ..
Venezuela, Bolivarian Republic of...    23
Viet Nam                                78
Yemen                                    6
Zambia                                   7
Zimbabwe                                 7
Name: LanguageHaveWorkedWith, Length: 177, dtype: int64

In [39]:
python_df = pd.concat([country_respondents,persons_in_country_uses_python], axis='columns',sort=False)

In [40]:
python_df

,count,LanguageHaveWorkedWith
Country,,
United States of America,7233,4221
Germany,3025,1685
India,2547,1162
United Kingdom of Great Britain and Northern Ireland,2042,1027
France,1409,820
...,...,...
Lesotho,1,1
Djibouti,1,0
Cape Verde,1,1
Palau,1,1
Guinea,1,1

In [45]:
python_df.rename(columns = {'count':'No of Respondents', 'LanguageHaveWorkedWith':'People Know python'}, inplace=True)

In [46]:
python_df['PercentagePeopleKnowsPython'] = (python_df['People Know python']/python_df['No of Respondents']) * 100

In [47]:
python_df

,No of Respondents,People Know python,PercentagePeopleKnowsPython
Country,,,
United States of America,7233,4221,58.357528
Germany,3025,1685,55.702479
India,2547,1162,45.622301
United Kingdom of Great Britain and Northern Ireland,2042,1027,50.293830
France,1409,820,58.197303
...,...,...,...
Lesotho,1,1,100.000000
Djibouti,1,0,0.000000
Cape Verde,1,1,100.000000
Palau,1,1,100.000000
Guinea,1,1,100.000000

In [48]:
python_df.head(50)

,No of Respondents,People Know python,PercentagePeopleKnowsPython
Country,,,
United States of America,7233,4221,58.357528
Germany,3025,1685,55.702479
India,2547,1162,45.622301
United Kingdom of Great Britain and Northern Ireland,2042,1027,50.293830
France,1409,820,58.197303
Canada,1305,687,52.643678
Ukraine,964,384,39.834025
Poland,888,459,51.689189
Netherlands,867,458,52.825836
Italy,835,436,52.215569
Brazil,825,407,49.333333
Australia,804,418,51.990050
Spain,717,398,55.509066
Sweden,616,291,47.240260
Switzerland,546,324,59.340659
Czech Republic,520,259,49.807692
Austria,410,222,54.146341
Romania,323,135,41.795666
Belgium,321,166,51.713396
Denmark,316,151,47.784810
Israel,297,173,58.249158
Turkey,295,130,44.067797
Mexico,286,140,48.951049
Portugal,280,155,55.357143
China,255,152,59.607843
New Zealand,255,136,53.333333
Finland,254,155,61.023622
South Africa,253,124,49.011858
Greece,252,115,45.634921
Bulgaria,244,107,43.852459
Pakistan,239,96,40.167364
Norway,237,110,46.413502
Hungary,236,120,50.847458
Argentina,222,108,48.648649
Bangladesh,220,88,40.000000
Ireland,209,104,49.760766
Colombia,202,113,55.940594
Russian Federation,200,110,55.000000
Nigeria,199,80,40.201005
Japan,188,101,53.723404
Indonesia,181,74,40.883978
Serbia,158,74,46.835443
"Iran, Islamic Republic of...",149,56,37.583893
Kenya,148,79,53.378378
Slovakia,147,77,52.380952
Viet Nam,145,78,53.793103
Philippines,142,70,49.295775
Egypt,140,45,32.142857
Chile,131,82,62.595420
Thailand,119,59,49.579832

In [50]:
python_df.loc['Japan']

No of Respondents              188.000000
People Know python             101.000000
PercentagePeopleKnowsPython     53.723404
Name: Japan, dtype: float64