In [1]:
import pandas as pd

In [2]:
people = { "first_name" : ["Smith","Rowan","Alfie"],
           "last_name" : ["Will","John","Haze"],
           "age" : ["34", "45","23"],
           "email" : ["smithwill@gmail.com", "rowanjohn@gmail.com", "alfiehaze@gmail.com"]}

In [4]:
people_df = pd.DataFrame(people)

In [5]:
people_df

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan      John  45  rowanjohn@gmail.com
2      Alfie      Haze  23  alfiehaze@gmail.com

In [17]:
people = { "first_name" : ["John","Rony"],
           "last_name" : ["Rake","Stobert"],
           "age" : ["44", "35"],
           "email" : ["johnrake@gmail.com", "ronystobert@gmail.com"]}

In [20]:
people_df2 = pd.DataFrame(people)

In [21]:
people_df2

  first_name last_name age                  email
0       John      Rake  44     johnrake@gmail.com
1       Rony   Stobert  35  ronystobert@gmail.com

In [6]:
people_df['first_name']+' '+people_df['last_name']

0    Smith Will
1    Rowan John
2    Alfie Haze
dtype: object

In [8]:


# adding new columns

people_df['full_name'] = people_df['first_name']+' '+people_df['last_name']

In [9]:
people_df

  first_name last_name age                email   full_name
0      Smith      Will  34  smithwill@gmail.com  Smith Will
1      Rowan      John  45  rowanjohn@gmail.com  Rowan John
2      Alfie      Haze  23  alfiehaze@gmail.com  Alfie Haze

In [12]:

# removing columns

people_df.drop(columns=["first_name","last_name"])

  age                email   full_name
0  34  smithwill@gmail.com  Smith Will
1  45  rowanjohn@gmail.com  Rowan John
2  23  alfiehaze@gmail.com  Alfie Haze

In [14]:

# splitting the values in a column and add it to new column

people_df['full_name'].str.split(' ', expand=True) # expand the list values in different columns

       0     1
0  Smith  Will
1  Rowan  John
2  Alfie  Haze

In [15]:

# to name the columns

people_df[["first","last"]] = people_df["full_name"].str.split(" ", expand = True)

In [16]:
people_df

  first_name last_name age                email   full_name  first  last
0      Smith      Will  34  smithwill@gmail.com  Smith Will  Smith  Will
1      Rowan      John  45  rowanjohn@gmail.com  Rowan John  Rowan  John
2      Alfie      Haze  23  alfiehaze@gmail.com  Alfie Haze  Alfie  Haze

In [26]:

# adding 2 dataframes

people_df = pd.concat([people_df, people_df2], ignore_index = True)

In [27]:
people_df

  first_name last_name age                  email   full_name  first  last
0      Smith      Will  34    smithwill@gmail.com  Smith Will  Smith  Will
1      Rowan      John  45    rowanjohn@gmail.com  Rowan John  Rowan  John
2      Alfie      Haze  23    alfiehaze@gmail.com  Alfie Haze  Alfie  Haze
3       John      Rake  44     johnrake@gmail.com         NaN    NaN   NaN
4       Rony   Stobert  35  ronystobert@gmail.com         NaN    NaN   NaN

In [28]:

# removing rows

people_df.drop(index=4)

  first_name last_name age                email   full_name  first  last
0      Smith      Will  34  smithwill@gmail.com  Smith Will  Smith  Will
1      Rowan      John  45  rowanjohn@gmail.com  Rowan John  Rowan  John
2      Alfie      Haze  23  alfiehaze@gmail.com  Alfie Haze  Alfie  Haze
3       John      Rake  44   johnrake@gmail.com         NaN    NaN   NaN

In [30]:

# removing rows that meets a specific condition

filt = people_df['last_name'] == 'Haze'
people_df.drop(index = people_df[filt].index)

  first_name last_name age                  email   full_name  first  last
0      Smith      Will  34    smithwill@gmail.com  Smith Will  Smith  Will
1      Rowan      John  45    rowanjohn@gmail.com  Rowan John  Rowan  John
3       John      Rake  44     johnrake@gmail.com         NaN    NaN   NaN
4       Rony   Stobert  35  ronystobert@gmail.com         NaN    NaN   NaN