In [1]:
import pandas as pd

In [3]:
people = { "first_name" : ["Smith","Rowan","Alfie"],
           "last_name" : ["Will","John","Haze"],
           "age" : ["34", "45","23"],
           "email" : ["smithwill@gmail.com", "rowanjohn@gmail.com", "alfiehaze@gmail.com"]}

In [4]:
people_df= pd.DataFrame(people)

In [5]:
people_df

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan      John  45  rowanjohn@gmail.com
2      Alfie      Haze  23  alfiehaze@gmail.com

In [6]:
people_df.set_index("email")

                    first_name last_name age
email
smithwill@gmail.com      Smith      Will  34
rowanjohn@gmail.com      Rowan      John  45
alfiehaze@gmail.com      Alfie      Haze  23

In [7]:
people_df

  first_name last_name age                email
0      Smith      Will  34  smithwill@gmail.com
1      Rowan      John  45  rowanjohn@gmail.com
2      Alfie      Haze  23  alfiehaze@gmail.com

In [9]:
people_df.set_index("email", inplace=True)

In [10]:
people_df

                    first_name last_name age
email
smithwill@gmail.com      Smith      Will  34
rowanjohn@gmail.com      Rowan      John  45
alfiehaze@gmail.com      Alfie      Haze  23

In [15]:
people_df.loc['smithwill@gmail.com']

first_name    Smith
last_name      Will
age              34
Name: smithwill@gmail.com, dtype: object

In [17]:
people_df.loc['smithwill@gmail.com', 'last_name']

'Will'

In [18]:
people_df.iloc[0]

first_name    Smith
last_name      Will
age              34
Name: smithwill@gmail.com, dtype: object

In [19]:
people_df.reset_index(inplace=True)

In [20]:
people_df

                 email first_name last_name age
0  smithwill@gmail.com      Smith      Will  34
1  rowanjohn@gmail.com      Rowan      John  45
2  alfiehaze@gmail.com      Alfie      Haze  23

In [44]:
filt = (people_df['last_name'] == 'Haze')

In [45]:
filt

0    False
1    False
2     True
Name: last_name, dtype: bool

In [47]:
people_df[filt]

                 email first_name last_name age
2  alfiehaze@gmail.com      Alfie      Haze  23

In [48]:
filt = (people_df['last_name']=='John') & (people_df['age']=='45')

In [49]:
people_df[filt]

                 email first_name last_name age
1  rowanjohn@gmail.com      Rowan      John  45

In [51]:
filt = (people_df['last_name'] == 'John') | (people_df['age'] == '45')

In [52]:
people_df[filt]

                 email first_name last_name age
1  rowanjohn@gmail.com      Rowan      John  45

In [54]:
filt = (people_df['last_name'] == 'John') | (people_df['age'] == '45')

In [55]:
people_df[~filt]

                 email first_name last_name age
0  smithwill@gmail.com      Smith      Will  34
2  alfiehaze@gmail.com      Alfie      Haze  23

In [2]:
df = pd.read_csv('survey_results_public.csv', low_memory=False)

In [3]:
df.shape

(49191, 172)

In [4]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=172)

In [5]:
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [25]:

# to set one of the unique column name as index

df = pd.read_csv('survey_results_public.csv', index_col = 'ResponseId', low_memory=False)

In [26]:
df.head()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [27]:
df.loc[2]

MainBranch                                I am a developer by profession
Age                                                      25-34 years old
EdLevel                              Associate degree (A.A., A.S., etc.)
Employment                                                      Employed
EmploymentAddl                                                       NaN
                                             ...
AIAgentExtWrite                                                      NaN
AIHuman                When I don’t trust AI’s answers;When I want to...
AIOpen                                         All skills. AI is a flop.
ConvertedCompYearly                                             104413.0
JobSat                                                               9.0
Name: 2, Length: 171, dtype: object

In [6]:
schema_df = pd.read_csv('survey_results_schema.csv')

In [7]:
schema_df

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...,...
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [30]:
schema_df.head()

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

In [31]:
schema_df.columns

Index(['qid', 'qname', 'question', 'type', 'sub', 'sq_id'], dtype='object')

In [32]:
schema_df = pd.read_csv('survey_results_schema.csv', index_col = 'qname')

In [33]:
schema_df.head()

,qid,question,type,sub,sq_id
qname,,,,,
TechEndorse_1,QID18,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
TechEndorse_2,QID18,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
TechEndorse_3,QID18,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
TechEndorse_4,QID18,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
TechEndorse_5,QID18,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

In [34]:
schema_df.loc['AIAgentExtWrite']

qid                                                    QID104
question    Was the out-of-the-box agents, copilots or ass...
type                                                       TE
sub                                                       NaN
sq_id                                                     NaN
Name: AIAgentExtWrite, dtype: object

In [35]:
schema_df.loc['AIAgentExtWrite','question']

'Was the out-of-the-box agents, copilots or assistants you used in the past year not listed above?  Please write them below separated by a comma and space if there are more than one.'

In [36]:

# sorting the index

schema_df.sort_index()

,qid,question,type,sub,sq_id
qname,,,,,
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
...,...,...,...,...,...
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN

In [37]:
schema_df

,qid,question,type,sub,sq_id
qname,,,,,
TechEndorse_1,QID18,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
TechEndorse_2,QID18,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
TechEndorse_3,QID18,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
TechEndorse_4,QID18,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
TechEndorse_5,QID18,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...
AIAgentObsWrite,QID103,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIHuman,QID100,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
AIOpen,QID93,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [38]:
schema_df.sort_index(ascending = False)

,qid,question,type,sub,sq_id
qname,,,,,
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
...,...,...,...,...,...
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN

In [39]:
schema_df.sort_index()

,qid,question,type,sub,sq_id
qname,,,,,
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
...,...,...,...,...,...
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN

In [40]:
schema_df.sort_index(inplace = True)

In [41]:
schema_df

,qid,question,type,sub,sq_id
qname,,,,,
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
...,...,...,...,...,...
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN

In [ ]:

# Filter

👉 Filter = keep what you want, remove the rest

Like:

Keep only students older than 25

Keep only rows with score > 80

Keep only some columns

In [56]:

schema_df.columns

Index(['qid', 'question', 'type', 'sub', 'sq_id'], dtype='object')

In [57]:
df.columns

Index(['MainBranch', 'Age', 'EdLevel', 'Employment', 'EmploymentAddl',
       'WorkExp', 'LearnCodeChoose', 'LearnCode', 'LearnCodeAI', 'AILearnHow',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=171)

In [58]:
df.head()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [61]:
high_salary = df['ConvertedCompYearly'] > 100000

In [62]:
df[high_salary]

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,GitHub Copilot,NaN,When I have ethical or security concerns about...,designing the architecture in the new domain,120000.0,7.0
26,I am a developer by profession,55-64 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,37.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Blogs or p...,...,NaN,NaN,NaN,NaN,ChatGPT;GitHub Copilot;Replit,NaN,When I don’t trust AI’s answers;When I want to...,Choosing the best solutions. Converting user r...,108913.0,8.0
27,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",None of the above,26.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,The ability to tackle more open ended problems...,162421.0,8.0
28,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",24.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,209643.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49008,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",Engaged in paid work (20-29 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I didn't spend time learning in the past year",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Communication with customer same as within the...,112334.0,10.0
49067,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",19.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Other onli...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,138470.0,6.0
49084,"I am not primarily a developer, but I write co...",35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,22.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188000.0,NaN
49085,"I am not primarily a developer, but I write co...",55-64 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Not employed,None of the above,46.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I didn't spend time learning in the past year",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119000.0,NaN
49089,I work with developers or my work supports dev...,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,15.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Blogs or p...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,280000.0,NaN

In [65]:
df.loc[high_salary,['Country','WorkExp','ConvertedCompYearly']]

,Country,WorkExp,ConvertedCompYearly
ResponseId,,,
2,Netherlands,2.0,104413.0
6,Ukraine,15.0,120000.0
26,United Kingdom of Great Britain and Northern I...,37.0,108913.0
27,Ireland,26.0,162421.0
28,Sweden,24.0,209643.0
...,...,...,...
49008,Czech Republic,19.0,112334.0
49067,Australia,19.0,138470.0
49084,United States of America,22.0,188000.0
49085,United States of America,46.0,119000.0
49089,United States of America,15.0,280000.0

In [9]:
# Filtering based on some countries

countries = ["India", "United Kingdom", "United States", "Germany", "Canada"]
filt = df['Country'].isin(countries)

In [10]:
df[filt]

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
13,14,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
15,16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",...,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,NaN,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,NaN,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,NaN,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
18,19,I am a developer by profession,35-44 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,20.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,AI will not become more capable in 3-5 years.,NaN,5.0
35,36,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,10.0,"Yes, I am not new to coding but am learning ne...",AI CodeGen tools or AI-enabled apps,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,problem solving,95132.0,6.0
46,47,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Volunteering (regularly),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49154,49155,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",Engaged in paid work (20-29 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
49155,49156,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc....",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,I think this will not obsolete to developer bu...,NaN,6.0
49175,49176,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,NaN,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,llama.cpp,Grafana + Prometheus,NaN,ChatGPT;Claude Code;Google Gemini,Cursor,When I don’t trust AI’s answers;When I want to...,Software Architecture,NaN,8.0
49178,49179,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,20.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,NaN,8.0
49180,49181,I am a developer by profession,18-24 years old,"Secondary school (e.g. American high school, G...",Student,Engaged in paid work (20-29 hours per week),1.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something;When...,NaN,NaN,9.0

In [12]:
df.loc[filt,'Country']

13         India
15         India
18       Germany
35       Germany
46         India
          ...
49154      India
49155      India
49175    Germany
49178    Germany
49180     Canada
Name: Country, Length: 6877, dtype: object

In [13]:

# checking whether a particular column exists in a DataFrame

"LanguageWorkedWith" in df.columns

False

In [14]:
df.shape

(49191, 172)

In [ ]:

# Scenario 

You have a very wide DataFrame (172 columns) and you want to:

Find if any column contains programming-language values
and return the column name(s)

🧠 Real-life idea

Imagine a big Excel sheet with 172 columns.
You don’t know which column is “Skills / Technology / Language”, but you know the values look like:

"Python", "Java", "C++", "JavaScript"

So we scan each column’s values and see if any of them contain programming languages.

In [15]:
languages = ["python"]

In [34]:

# Search only for python

python_columns = []

for col in df.columns:
    if df[col].astype(str).str.contains("python", case=False, na=False).any():
        python_columns.append(col)

python_columns

['TechEndorse_13_TEXT',
 'TechOppose_15_TEXT',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LanguageAdmired',
 'LanguagesHaveEntry',
 'LanguagesWantEntry',
 'DatabaseHaveEntry',
 'PlatformHaveEntry',
 'PlatformWantEntry',
 'WebframeHaveEntry',
 'WebframeWantEntry',
 'DevEnvHaveEntry',
 'DevEnvWantEntry',
 'SOTagsHaveEntry',
 'SOTagsWant Entry',
 'OfficeStackHaveEntry',
 'OfficeStackWantEntry',
 'CommPlatformHaveEntr',
 'CommPlatformWantEntr',
 'AIExplain',
 'AIAgentKnowWrite',
 'AIAgentExtWrite',
 'AIOpen']

In [16]:

# Search for any programming language

cols_with_languages = []

for col in df.columns:
    # convert column to string & lowercase (safe for mixed data)
    values = df[col].astype(str).str.lower()
    
    if values.str.contains('|'.join(languages), na=False).any():
        cols_with_languages.append(col)

cols_with_languages

['TechEndorse_13_TEXT',
 'TechOppose_15_TEXT',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LanguageAdmired',
 'LanguagesHaveEntry',
 'LanguagesWantEntry',
 'DatabaseHaveEntry',
 'PlatformHaveEntry',
 'PlatformWantEntry',
 'WebframeHaveEntry',
 'WebframeWantEntry',
 'DevEnvHaveEntry',
 'DevEnvWantEntry',
 'SOTagsHaveEntry',
 'SOTagsWant Entry',
 'OfficeStackHaveEntry',
 'OfficeStackWantEntry',
 'CommPlatformHaveEntr',
 'CommPlatformWantEntr',
 'AIExplain',
 'AIAgentKnowWrite',
 'AIAgentExtWrite',
 'AIOpen']

In [17]:

# If you want to see SAMPLE values from those columns

for col in cols_with_languages:
    print(f"\nColumn: {col}")
    print(df[col].dropna().unique()[:10])

Column: TechEndorse_13_TEXT
['usefullness' 'Currently maintained' 'European'
 'User friendly and flows well'
 'Cutoff: Anything below this is a BAD THIGN'
 'Good youtube tutorials, endorsed by Youtubers I watch'
 'Good community support' 'Not having AI'
 'Well-written public documentation'
 'Lack of AI integration and other data harvesting']

Column: TechOppose_15_TEXT
['AI' 'Presence of AI or AI agents' 'Pushing AI Features'
 'Heavy AI integration' 'Bogus AI integration'
 'Cutoff: Below this is a GOOD THING' 'Having AI' 'Lack of user community'
 'AI integration' 'AI nonsense']

Column: LanguageHaveWorkedWith
['Bash/Shell (all shells);Dart;SQL' 'Java'
 'Dart;HTML/CSS;JavaScript;TypeScript' 'Java;Kotlin;SQL'
 'C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;PowerShell;Python;SQL;TypeScript;VBA;Visual Basic (.Net)'
 'Java;Scala' 'JavaScript;TypeScript'
 'Bash/Shell (all shells);HTML/CSS;JavaScript;Python;SQL;TypeScript'
 'Java;Python;Scala' 'HTML/CSS;Java;JavaScript;SQL;TypeScript']

Column: LanguageWantToWorkWith
['Dart' 'Java;Python;Swift' 'Dart;HTML/CSS;JavaScript;TypeScript'
 'Java;Kotlin' 'C#;Java;JavaScript;Python;SQL;TypeScript'
 'Java;Kotlin;Scala' 'JavaScript;TypeScript'
 'Assembly;Bash/Shell (all shells);HTML/CSS;JavaScript;Python;Ruby;SQL;TypeScript'
 'Scala' 'HTML/CSS;Java;JavaScript;SQL;TypeScript']

Column: LanguageAdmired
['Dart' 'Java' 'Dart;HTML/CSS;JavaScript;TypeScript' 'Java;Kotlin'
 'C#;Java;JavaScript;Python;SQL;TypeScript' 'Java;Scala'
 'JavaScript;TypeScript'
 'Bash/Shell (all shells);HTML/CSS;JavaScript;Python;SQL;TypeScript'
 'Scala' 'HTML/CSS;Java;JavaScript;SQL;TypeScript']

Column: LanguagesHaveEntry
['5' 'MQL4' 'Pascal, PL/I, REXX' 'Haskell' 'Typescript' 'Bash'
 'Dream Maker Language'
 'Nim, Answer set programming (ASP), System Verilog' 'BrightScript' 'CUDA']

Column: LanguagesWantEntry
['1' 'MQL5' 'Pascal, PL/I, REXX' 'Typescript'
 'Nim, Answer set programming (ASP), System Verilog' 'warp' 'VimScript'
 'Verilog' 'pureBasic' 'Clojure, Clojurescript']

Column: DatabaseHaveEntry
['5' 'D1, NeonDB' 'tableplus' 'SQL Server' 'Sap hana' 'Data bricks python'
 'Progress OpenEdge' 'Convex' 'Mimer SQL' 'Microsoft Dataverse']

Column: PlatformHaveEntry
['5' 'Openshift' 'hex' 'condo, mamba, micromamba' 'Expo, Nix' 'Dynatrace'
 'Hetzner Cloud' 'CircleCI' 'OracleCloud' 'uv']

Column: PlatformWantEntry
['4' 'hex' 'condo, mamba, micromamba' 'CircleCI' 'uv' 'Cloudflare workers'
 'Azure' 'Opentofu' 'Sbt, mill' 'Vercel']

Column: WebframeHaveEntry
['akka' '4' 'Perl Dancer' 'Remix, Capacitor, Ionic' 'htmx' 'gin' 'Hono'
 'Alpine.js' 'Bootstrap' 'cot.rs']

Column: WebframeWantEntry
['Solid.js' 'akka' '4' 'Perl Dancer' 'Ash' 'FastHTML' 'HTMLX' 'htmx'
 'Falcon' 'gin']

Column: DevEnvHaveEntry
['Emacs' 'c++ builder' 'emacs' 'OpenAI Api' 'GoLand' 'RubyMine' 'micro'
 'CLion' 'Void' 'Mendix Studio Pro']

Column: DevEnvWantEntry
['Emacs' 'emacs' 'GoLand' 'RubyMine' 'micro' 'Void' 'Eclipse Theia'
 'Helix' 'Codelite' 'warp']

Column: SOTagsHaveEntry
['5' 'None of these' 'OpenMP, ROCm, Level Zero' 'DaisyUI' 'GitHub Copilot'
 'Ollama' '2' '.net 8' 'ionic' "DSL's"]

Column: SOTagsWant Entry
['4' 'Not listed' 'DaisyUI' 'GitHub Copilot' 'Ollama' 'ag-grid' '2' 'MCP'
 'ionic' 'Power Automate']

Column: OfficeStackHaveEntry
['4' 'No' 'Whimsical' 'BitBucket' 'Bitbucket' 'Microsoft TFS' 'Codeberg'
 'Figma' 'Gitea' 'hgweb']

Column: OfficeStackWantEntry
['5' 'No' 'Whimsical' 'Bitbucket' 'Codeberg' 'Agent force, manus'
 'Forjego' 'hgweb' 'sorcehut' 'Gitea']

Column: CommPlatformHaveEntr
['5' 'Codidact' 'Discourse (Rust forum)' 'Fediverse / Mastodon' 'Twitter'
 'lobste.rs' 'Matrix' 'Mastodon'
 'https://app.daily.dev/,fediverse, mastodon' 'Microsoft Teams']

Column: CommPlatformWantEntr
['5' 'Mastodon' 'Codidact' 'LinkedIn' 'Discourse (Rust forum)'
 'Fediverse / Mastodon' 'Matrix'
 'fediverse stuff (mastodon, pixelfed, lemmy, etc)' 'Mastodon, Instagram'
 'Telegram']

Column: AIExplain
['No' 'NO' 'partly' 'No it isnt' 'Yes' 'No.'
 "When I need to prototype something then yes it's part of my professional development work. \nBut when it's about maintenance or adding new features I'm not relying on vibe coding because it misses a lot of important things."
 'yes' 'no'
 "No. I find it to be useless, unless I'm starting a brand new project."]

Column: AIAgentKnowWrite
['ollama' 'copilot' 'opensearch' 'LangChain, LangGraph, Elasticsearch'
 'Junie from jetbrains' 'AgentForce' "Claude's Sonnet 4" 'custom'
 'ADA for Slack' 'Aider, OpenAI Codex, custom made agent for internal use']

Column: AIAgentExtWrite
['Cursor' 'codeium, windsurf' 'warp' 'Jetbrains AI' 'junie' 'Windsurf'
 'Junie' 'xAI Grok' 'SourceCraft' 'Zed Pro']

Column: AIOpen
['Troubleshooting, profiling, debugging' 'All skills. AI is a flop.'
 'Understand how things actually work, problem solving, and algorithms'
 'critical thinking, the skill to define the task correctly'
 'designing the architecture in the new domain'
 'Innovation, system design'
 'Code writing. I know this sounds weird but you would still need to debug and if you do not understand code then you are in trouble. \n\nDesign/architecture principles. When AI gives you an answer you are responsible for the code not AI. So you must have broader picture of how things work. Error handling, security, high load - non functional requirements in general. \n\nAnd most important of all will be Critical Thinking. Ability to think will always be valuable.'
 'senior development' '5'
 'All the ones that INTELLIGENT programmers currently use']

In [18]:
python_columns = []

for col in df.columns:
    if df[col].astype(str).str.contains("python", case=False, na=False).any():
        # If any value in this column contains at least one programming language then append it to the following list
        python_columns.append(col)

python_columns

['TechEndorse_13_TEXT',
 'TechOppose_15_TEXT',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LanguageAdmired',
 'LanguagesHaveEntry',
 'LanguagesWantEntry',
 'DatabaseHaveEntry',
 'PlatformHaveEntry',
 'PlatformWantEntry',
 'WebframeHaveEntry',
 'WebframeWantEntry',
 'DevEnvHaveEntry',
 'DevEnvWantEntry',
 'SOTagsHaveEntry',
 'SOTagsWant Entry',
 'OfficeStackHaveEntry',
 'OfficeStackWantEntry',
 'CommPlatformHaveEntr',
 'CommPlatformWantEntr',
 'AIExplain',
 'AIAgentKnowWrite',
 'AIAgentExtWrite',
 'AIOpen']

In [21]:
filt = df['LanguageHaveWorkedWith'].str.contains('python',na=False)

In [24]:
df.loc[filt,'LanguageHaveWorkedWith']

Series([], Name: LanguageHaveWorkedWith, dtype: object)

In [25]:
df[filt]

Empty DataFrame
Columns: [ResponseId, MainBranch, Age, EdLevel, Employment, EmploymentAddl, WorkExp, LearnCodeChoose, LearnCode, LearnCodeAI, AILearnHow, YearsCode, DevType, OrgSize, ICorPM, RemoteWork, PurchaseInfluence, TechEndorseIntro, TechEndorse_1, TechEndorse_2, TechEndorse_3, TechEndorse_4, TechEndorse_5, TechEndorse_6, TechEndorse_7, TechEndorse_8, TechEndorse_9, TechEndorse_13, TechEndorse_13_TEXT, TechOppose_1, TechOppose_2, TechOppose_3, TechOppose_5, TechOppose_7, TechOppose_9, TechOppose_11, TechOppose_13, TechOppose_16, TechOppose_15, TechOppose_15_TEXT, Industry, JobSatPoints_1, JobSatPoints_2, JobSatPoints_3, JobSatPoints_4, JobSatPoints_5, JobSatPoints_6, JobSatPoints_7, JobSatPoints_8, JobSatPoints_9, JobSatPoints_10, JobSatPoints_11, JobSatPoints_13, JobSatPoints_14, JobSatPoints_15, JobSatPoints_16, JobSatPoints_15_TEXT, AIThreat, NewRole, ToolCountWork, ToolCountPersonal, Country, Currency, CompTotal, LanguageChoice, LanguageHaveWorkedWith, LanguageWantToWorkWith, LanguageAdmired, LanguagesHaveEntry, LanguagesWantEntry, DatabaseChoice, DatabaseHaveWorkedWith, DatabaseWantToWorkWith, DatabaseAdmired, DatabaseHaveEntry, DatabaseWantEntry, PlatformChoice, PlatformHaveWorkedWith, PlatformWantToWorkWith, PlatformAdmired, PlatformHaveEntry, PlatformWantEntry, WebframeChoice, WebframeHaveWorkedWith, WebframeWantToWorkWith, WebframeAdmired, WebframeHaveEntry, WebframeWantEntry, DevEnvsChoice, DevEnvsHaveWorkedWith, DevEnvsWantToWorkWith, DevEnvsAdmired, DevEnvHaveEntry, DevEnvWantEntry, SOTagsHaveWorkedWith, SOTagsWantToWorkWith, SOTagsAdmired, SOTagsHaveEntry, SOTagsWant Entry, OpSysPersonal use, ...]
Index: []

[0 rows x 172 columns]

In [26]:
df['LanguageHaveWorkedWith']

0                         Bash/Shell (all shells);Dart;SQL
1                                                     Java
2                      Dart;HTML/CSS;JavaScript;TypeScript
3                                          Java;Kotlin;SQL
4        C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
                               ...
49186                                                  NaN
49187                                                  NaN
49188                                                  NaN
49189                                                  NaN
49190                                                  NaN
Name: LanguageHaveWorkedWith, Length: 49191, dtype: object


# str.contains()

str.contains() is a pandas string method used to check whether a piece of text exists inside each value of a column.

👉 It returns True or False for every row.

👉 It checks whether a text appears inside each value of a column.

Think of it like:

“Does this cell contain this word or not?”

🧠 Real-life analogy

Imagine a list of messages:

Message
"I love Python"
"Java developer"
"Python & SQL"

If you ask:

“Which messages contain the word Python?”

That’s exactly what str.contains() does.

🔍 What it actually does

For each row:

Looks inside the text

Checks if "Python" appears anywhere

Returns True if yes, False if no

⚠️ Handle missing values (important)

df["skills"].str.contains("Python", na=False)

Without na=False, missing values (NaN) cause issues.

🔡 Case-insensitive search

df["skills"].str.contains("python", case=False, na=False)


Matches:

Python

PYTHON

python

In [32]:
 df['LanguageHaveWorkedWith'].str.contains('Python', case=False, na=False)

0        False
1        False
2        False
3        False
4         True
         ...
49186    False
49187    False
49188    False
49189    False
49190    False
Name: LanguageHaveWorkedWith, Length: 49191, dtype: bool

In [33]:
filt = df['LanguageHaveWorkedWith'].str.contains('Python', case=False, na=False)

In [31]:
df.loc[filt,'LanguageHaveWorkedWith']

4        C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
7        Bash/Shell (all shells);HTML/CSS;JavaScript;Py...
8                                        Java;Python;Scala
15       Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...
17                          HTML/CSS;JavaScript;Python;SQL
                               ...
49143            HTML/CSS;JavaScript;Python;SQL;TypeScript
49145    Assembly;Bash/Shell (all shells);C;C++;Python;...
49175    Bash/Shell (all shells);C#;C++;GDScript;HTML/C...
49176    Bash/Shell (all shells);HTML/CSS;JavaScript;Py...
49177    Bash/Shell (all shells);HTML/CSS;Lisp;PowerShe...
Name: LanguageHaveWorkedWith, Length: 18466, dtype: object

In [6]:
df['ConvertedCompYearly']

0         61256.0
1        104413.0
2         53061.0
3         36197.0
4         60000.0
           ...
49186         NaN
49187         NaN
49188         NaN
49189         NaN
49190         NaN
Name: ConvertedCompYearly, Length: 49191, dtype: float64

In [4]:
'ConvertedComp' in df.columns

False

In [5]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=172)

In [12]:
df.rename(columns={'ConvertedCompYearly':"SalaryUSD"},inplace=True)

In [13]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'SalaryUSD', 'JobSat'],
      dtype='object', length=172)

In [14]:
df['SalaryUSD']

0         61256.0
1        104413.0
2         53061.0
3         36197.0
4         60000.0
           ...
49186         NaN
49187         NaN
49188         NaN
49189         NaN
49190         NaN
Name: SalaryUSD, Length: 49191, dtype: float64

In [ ]:
df['Hobbyist'].map({"Yes":"True","No":"False"})

In [15]:
'Hobbyist' in df.columns

False